package com.example.example

import com.example.currencyconverter.domain.models.currencyapiservice.currency.currencies.*
import com.google.gson.annotations.SerializedName

data class Data(

    @SerializedName("AED") var AED: AED = AED(),
    @SerializedName("AFN") var AFN: AFN = AFN(),
    @SerializedName("ALL") var ALL: ALL = ALL(),
    @SerializedName("AMD") var AMD: AMD = AMD(),
    @SerializedName("ANG") var ANG: ANG = ANG(),
    @SerializedName("AOA") var AOA: AOA = AOA(),
    @SerializedName("ARS") var ARS: ARS = ARS(),
    @SerializedName("AUD") var AUD: AUD = AUD(),
    @SerializedName("AWG") var AWG: AWG = AWG(),
    @SerializedName("AZN") var AZN: AZN = AZN(),
    @SerializedName("BAM") var BAM: BAM = BAM(),
    @SerializedName("BBD") var BBD: BBD = BBD(),
    @SerializedName("BDT") var BDT: BDT = BDT(),
    @SerializedName("BGN") var BGN: BGN = BGN(),
    @SerializedName("BHD") var BHD: BHD = BHD(),
    @SerializedName("BIF") var BIF: BIF = BIF(),
    @SerializedName("BIH") var BIH: BIH = BIH(),
    @SerializedName("BMD") var BMD: BMD = BMD(),
    @SerializedName("BND") var BND: BND = BND(),
    @SerializedName("BOB") var BOB: BOB = BOB(),
    @SerializedName("BRL") var BRL: BRL = BRL(),
    @SerializedName("BSD") var BSD: BSD = BSD(),
    @SerializedName("BTC") var BTC: BTC = BTC(),
    @SerializedName("BTN") var BTN: BTN = BTN(),
    @SerializedName("BWP") var BWP: BWP = BWP(),
    @SerializedName("BYN") var BYN: BYN = BYN(),
    @SerializedName("BYR") var BYR: BYR = BYR(),
    @SerializedName("BZD") var BZD: BZD = BZD(),
    @SerializedName("CAD") var CAD: CAD = CAD(),
    @SerializedName("CDF") var CDF: CDF = CDF(),
    @SerializedName("CHF") var CHF: CHF = CHF(),
    @SerializedName("CLF") var CLF: CLF = CLF(),
    @SerializedName("CLP") var CLP: CLP = CLP(),
    @SerializedName("CNY") var CNY: CNY = CNY(),
    @SerializedName("COP") var COP: COP = COP(),
    @SerializedName("CRC") var CRC: CRC = CRC(),
    @SerializedName("CUC") var CUC: CUC = CUC(),
    @SerializedName("CUP") var CUP: CUP = CUP(),
    @SerializedName("CVE") var CVE: CVE = CVE(),
    @SerializedName("CZK") var CZK: CZK = CZK(),
    @SerializedName("DJF") var DJF: DJF = DJF(),
    @SerializedName("DKK") var DKK: DKK = DKK(),
    @SerializedName("DOP") var DOP: DOP = DOP(),
    @SerializedName("DZD") var DZD: DZD = DZD(),
    @SerializedName("EGP") var EGP: EGP = EGP(),
    @SerializedName("ERN") var ERN: ERN = ERN(),
    @SerializedName("ETB") var ETB: ETB = ETB(),
    @SerializedName("ETH") var ETH: ETH = ETH(),
    @SerializedName("EUR") var EUR: EUR = EUR(),
    @SerializedName("FJD") var FJD: FJD = FJD(),
    @SerializedName("FKP") var FKP: FKP = FKP(),
    @SerializedName("GBP") var GBP: GBP = GBP(),
    @SerializedName("GEL") var GEL: GEL = GEL(),
    @SerializedName("GGP") var GGP: GGP = GGP(),
    @SerializedName("GHS") var GHS: GHS = GHS(),
    @SerializedName("GIP") var GIP: GIP = GIP(),
    @SerializedName("GMD") var GMD: GMD = GMD(),
    @SerializedName("GNF") var GNF: GNF = GNF(),
    @SerializedName("GTQ") var GTQ: GTQ = GTQ(),
    @SerializedName("GYD") var GYD: GYD = GYD(),
    @SerializedName("HKD") var HKD: HKD = HKD(),
    @SerializedName("HNL") var HNL: HNL = HNL(),
    @SerializedName("HRK") var HRK: HRK = HRK(),
    @SerializedName("HRV") var HRV: HRV = HRV(),
    @SerializedName("HTG") var HTG: HTG = HTG(),
    @SerializedName("HUF") var HUF: HUF = HUF(),
    @SerializedName("IDR") var IDR: IDR = IDR(),
    @SerializedName("ILS") var ILS: ILS = ILS(),
    @SerializedName("IMP") var IMP: IMP = IMP(),
    @SerializedName("INR") var INR: INR = INR(),
    @SerializedName("IQD") var IQD: IQD = IQD(),
    @SerializedName("IRR") var IRR: IRR = IRR(),
    @SerializedName("ISK") var ISK: ISK = ISK(),
    @SerializedName("JEP") var JEP: JEP = JEP(),
    @SerializedName("JMD") var JMD: JMD = JMD(),
    @SerializedName("JOD") var JOD: JOD = JOD(),
    @SerializedName("JPY") var JPY: JPY = JPY(),
    @SerializedName("KES") var KES: KES = KES(),
    @SerializedName("KGS") var KGS: KGS = KGS(),
    @SerializedName("KHR") var KHR: KHR = KHR(),
    @SerializedName("KMF") var KMF: KMF = KMF(),
    @SerializedName("KPW") var KPW: KPW = KPW(),
    @SerializedName("KRW") var KRW: KRW = KRW(),
    @SerializedName("KWD") var KWD: KWD = KWD(),
    @SerializedName("KYD") var KYD: KYD = KYD(),
    @SerializedName("KZT") var KZT: KZT = KZT(),
    @SerializedName("LAK") var LAK: LAK = LAK(),
    @SerializedName("LBP") var LBP: LBP = LBP(),
    @SerializedName("LKR") var LKR: LKR = LKR(),
    @SerializedName("LRD") var LRD: LRD = LRD(),
    @SerializedName("LSL") var LSL: LSL = LSL(),
    @SerializedName("LTC") var LTC: LTC = LTC(),
    @SerializedName("LTL") var LTL: LTL = LTL(),
    @SerializedName("LVL") var LVL: LVL = LVL(),
    @SerializedName("LYD") var LYD: LYD = LYD(),
    @SerializedName("MAD") var MAD: MAD = MAD(),
    @SerializedName("MDL") var MDL: MDL = MDL(),
    @SerializedName("MGA") var MGA: MGA = MGA(),
    @SerializedName("MKD") var MKD: MKD = MKD(),
    @SerializedName("MMK") var MMK: MMK = MMK(),
    @SerializedName("MNT") var MNT: MNT = MNT(),
    @SerializedName("MOP") var MOP: MOP = MOP(),
    @SerializedName("MRO") var MRO: MRO = MRO(),
    @SerializedName("MUR") var MUR: MUR = MUR(),
    @SerializedName("MVR") var MVR: MVR = MVR(),
    @SerializedName("MWK") var MWK: MWK = MWK(),
    @SerializedName("MXN") var MXN: MXN = MXN(),
    @SerializedName("MYR") var MYR: MYR = MYR(),
    @SerializedName("MZN") var MZN: MZN = MZN(),
    @SerializedName("NAD") var NAD: NAD = NAD(),
    @SerializedName("NGN") var NGN: NGN = NGN(),
    @SerializedName("NIO") var NIO: NIO = NIO(),
    @SerializedName("NOK") var NOK: NOK = NOK(),
    @SerializedName("NPR") var NPR: NPR = NPR(),
    @SerializedName("NZD") var NZD: NZD = NZD(),
    @SerializedName("OMR") var OMR: OMR = OMR(),
    @SerializedName("PAB") var PAB: PAB = PAB(),
    @SerializedName("PEN") var PEN: PEN = PEN(),
    @SerializedName("PGK") var PGK: PGK = PGK(),
    @SerializedName("PHP") var PHP: PHP = PHP(),
    @SerializedName("PKR") var PKR: PKR = PKR(),
    @SerializedName("PLN") var PLN: PLN = PLN(),
    @SerializedName("PYG") var PYG: PYG = PYG(),
    @SerializedName("QAR") var QAR: QAR = QAR(),
    @SerializedName("RON") var RON: RON = RON(),
    @SerializedName("RSD") var RSD: RSD = RSD(),
    @SerializedName("RUB") var RUB: RUB = RUB(),
    @SerializedName("RWF") var RWF: RWF = RWF(),
    @SerializedName("SAR") var SAR: SAR = SAR(),
    @SerializedName("SBD") var SBD: SBD = SBD(),
    @SerializedName("SCR") var SCR: SCR = SCR(),
    @SerializedName("SDG") var SDG: SDG = SDG(),
    @SerializedName("SEK") var SEK: SEK = SEK(),
    @SerializedName("SGD") var SGD: SGD = SGD(),
    @SerializedName("SHP") var SHP: SHP = SHP(),
    @SerializedName("SLL") var SLL: SLL = SLL(),
    @SerializedName("SOS") var SOS: SOS = SOS(),
    @SerializedName("SRD") var SRD: SRD = SRD(),
    @SerializedName("SSP") var SSP: SSP = SSP(),
    @SerializedName("STD") var STD: STD = STD(),
    @SerializedName("SVC") var SVC: SVC = SVC(),
    @SerializedName("SYP") var SYP: SYP = SYP(),
    @SerializedName("SZL") var SZL: SZL = SZL(),
    @SerializedName("THB") var THB: THB = THB(),
    @SerializedName("TJS") var TJS: TJS = TJS(),
    @SerializedName("TMT") var TMT: TMT = TMT(),
    @SerializedName("TND") var TND: TND = TND(),
    @SerializedName("TOP") var TOP: TOP = TOP(),
    @SerializedName("TRY") var TRY: TRY = TRY(),
    @SerializedName("TTD") var TTD: TTD = TTD(),
    @SerializedName("TWD") var TWD: TWD = TWD(),
    @SerializedName("TZS") var TZS: TZS = TZS(),
    @SerializedName("UAH") var UAH: UAH = UAH(),
    @SerializedName("UGX") var UGX: UGX = UGX(),
    @SerializedName("URY") var URY: URY = URY(),
    @SerializedName("USD") var USD: USD = USD(),
    @SerializedName("UYU") var UYU: UYU = UYU(),
    @SerializedName("UZS") var UZS: UZS = UZS(),
    @SerializedName("VEF") var VEF: VEF = VEF(),
    @SerializedName("VND") var VND: VND = VND(),
    @SerializedName("VUV") var VUV: VUV = VUV(),
    @SerializedName("WST") var WST: WST = WST(),
    @SerializedName("XAF") var XAF: XAF = XAF(),
    @SerializedName("XAG") var XAG: XAG = XAG(),
    @SerializedName("XAU") var XAU: XAU = XAU(),
    @SerializedName("XCD") var XCD: XCD = XCD(),
    @SerializedName("XDR") var XDR: XDR = XDR(),
    @SerializedName("XOF") var XOF: XOF = XOF(),
    @SerializedName("XPF") var XPF: XPF = XPF(),
    @SerializedName("XRP") var XRP: XRP = XRP(),
    @SerializedName("YER") var YER: YER = YER(),
    @SerializedName("ZAR") var ZAR: ZAR = ZAR(),
    @SerializedName("ZMK") var ZMK: ZMK = ZMK(),
    @SerializedName("ZMW") var ZMW: ZMW = ZMW(),
    @SerializedName("ZWL") var ZWL: ZWL = ZWL()

)

fun Data.toMap(): Map<String, String> {
    val map = mutableMapOf<String, String>()
    map["AED"] = this.AED.name ?: ""
    map["AFN"] = this.AFN.name ?: ""
    map["ALL"] = this.ALL.name ?: ""
    map["AMD"] = this.AMD.name ?: ""
    map["ANG"] = this.ANG.name ?: ""
    map["AOA"] = this.AOA.name ?: ""
    map["ARS"] = this.ARS.name ?: ""
    map["AUD"] = this.AUD.name ?: ""
    map["AWG"] = this.AWG.name ?: ""
    map["AZN"] = this.AZN.name ?: ""
    map["BAM"] = this.BAM.name ?: ""
    map["BBD"] = this.BBD.name ?: ""
    map["BDT"] = this.BDT.name ?: ""
    map["BGN"] = this.BGN.name ?: ""
    map["BHD"] = this.BHD.name ?: ""
    map["BIF"] = this.BIF.name ?: ""
    map["BIH"] = this.BIH.name ?: ""
    map["BMD"] = this.BMD.name ?: ""
    map["BND"] = this.BND.name ?: ""
    map["BOB"] = this.BOB.name ?: ""
    map["BRL"] = this.BRL.name ?: ""
    map["BSD"] = this.BSD.name ?: ""
    map["BTC"] = this.BTC.name ?: ""
    map["BTN"] = this.BTN.name ?: ""
    map["BWP"] = this.BWP.name ?: ""
    map["BYN"] = this.BYN.name ?: ""
    map["BYR"] = this.BYR.name ?: ""
    map["BZD"] = this.BZD.name ?: ""
    map["CAD"] = this.CAD.name ?: ""
    map["CDF"] = this.CDF.name ?: ""
    map["CHF"] = this.CHF.name ?: ""
    map["CLF"] = this.CLF.name ?: ""
    map["CLP"] = this.CLP.name ?: ""
    map["CNY"] = this.CNY.name ?: ""
    map["COP"] = this.COP.name ?: ""
    map["CRC"] = this.CRC.name ?: ""
    map["CUC"] = this.CUC.name ?: ""
    map["CUP"] = this.CUP.name ?: ""
    map["CVE"] = this.CVE.name ?: ""
    map["CZK"] = this.CZK.name ?: ""
    map["DJF"] = this.DJF.name ?: ""
    map["DKK"] = this.DKK.name ?: ""
    map["DOP"] = this.DOP.name ?: ""
    map["DZD"] = this.DZD.name ?: ""
    map["EGP"] = this.EGP.name ?: ""
    map["ERN"] = this.ERN.name ?: ""
    map["ETB"] = this.ETB.name ?: ""
    map["ETH"] = this.ETH.name ?: ""
    map["EUR"] = this.EUR.name ?: ""
    map["FJD"] = this.FJD.name ?: ""
    map["FKP"] = this.FKP.name ?: ""
    map["GBP"] = this.GBP.name ?: ""
    map["GEL"] = this.GEL.name ?: ""
    map["GGP"] = this.GGP.name ?: ""
    map["GHS"] = this.GHS.name ?: ""
    map["GIP"] = this.GIP.name ?: ""
    map["GMD"] = this.GMD.name ?: ""
    map["GNF"] = this.GNF.name ?: ""
    map["GTQ"] = this.GTQ.name ?: ""
    map["GYD"] = this.GYD.name ?: ""
    map["HKD"] = this.HKD.name ?: ""
    map["HNL"] = this.HNL.name ?: ""
    map["HRK"] = this.HRK.name ?: ""
    map["HRV"] = this.HRV.name ?: ""
    map["HTG"] = this.HTG.name ?: ""
    map["HUF"] = this.HUF.name ?: ""
    map["IDR"] = this.IDR.name ?: ""
    map["ILS"] = this.ILS.name ?: ""
    map["IMP"] = this.IMP.name ?: ""
    map["INR"] = this.INR.name ?: ""
    map["IQD"] = this.IQD.name ?: ""
    map["IRR"] = this.IRR.name ?: ""
    map["ISK"] = this.ISK.name ?: ""
    map["JEP"] = this.JEP.name ?: ""
    map["JMD"] = this.JMD.name ?: ""
    map["JOD"] = this.JOD.name ?: ""
    map["JPY"] = this.JPY.name ?: ""
    map["KES"] = this.KES.name ?: ""
    map["KGS"] = this.KGS.name ?: ""
    map["KHR"] = this.KHR.name ?: ""
    map["KMF"] = this.KMF.name ?: ""
    map["KPW"] = this.KPW.name ?: ""
    map["KRW"] = this.KRW.name ?: ""
    map["KWD"] = this.KWD.name ?: ""
    map["KYD"] = this.KYD.name ?: ""
    map["KZT"] = this.KZT.name ?: ""
    map["LAK"] = this.LAK.name ?: ""
    map["LBP"] = this.LBP.name ?: ""
    map["LKR"] = this.LKR.name ?: ""
    map["LRD"] = this.LRD.name ?: ""
    map["LSL"] = this.LSL.name ?: ""
    map["LTC"] = this.LTC.name ?: ""
    map["LTL"] = this.LTL.name ?: ""
    map["LVL"] = this.LVL.name ?: ""
    map["LYD"] = this.LYD.name ?: ""
    map["MAD"] = this.MAD.name ?: ""
    map["MDL"] = this.MDL.name ?: ""
    map["MGA"] = this.MGA.name ?: ""
    map["MKD"] = this.MKD.name ?: ""
    map["MMK"] = this.MMK.name ?: ""
    map["MNT"] = this.MNT.name ?: ""
    map["MOP"] = this.MOP.name ?: ""
    map["MRO"] = this.MRO.name ?: ""
    map["MUR"] = this.MUR.name ?: ""
    map["MVR"] = this.MVR.name ?: ""
    map["MWK"] = this.MWK.name ?: ""
    map["MXN"] = this.MXN.name ?: ""
    map["MYR"] = this.MYR.name ?: ""
    map["MZN"] = this.MZN.name ?: ""
    map["NAD"] = this.NAD.name ?: ""
    map["NGN"] = this.NGN.name ?: ""
    map["NIO"] = this.NIO.name ?: ""
    map["NOK"] = this.NOK.name ?: ""
    map["NPR"] = this.NPR.name ?: ""
    map["NZD"] = this.NZD.name ?: ""
    map["OMR"] = this.OMR.name ?: ""
    map["PAB"] = this.PAB.name ?: ""
    map["PEN"] = this.PEN.name ?: ""
    map["PGK"] = this.PGK.name ?: ""
    map["PHP"] = this.PHP.name ?: ""
    map["PKR"] = this.PKR.name ?: ""
    map["PLN"] = this.PLN.name ?: ""
    map["PYG"] = this.PYG.name ?: ""
    map["QAR"] = this.QAR.name ?: ""
    map["RON"] = this.RON.name ?: ""
    map["RSD"] = this.RSD.name ?: ""
    map["RUB"] = this.RUB.name ?: ""
    map["RWF"] = this.RWF.name ?: ""
    map["SAR"] = this.SAR.name ?: ""
    map["SBD"] = this.SBD.name ?: ""
    map["SCR"] = this.SCR.name ?: ""
    map["SDG"] = this.SDG.name ?: ""
    map["SEK"] = this.SEK.name ?: ""
    map["SGD"] = this.SGD.name ?: ""
    map["SHP"] = this.SHP.name ?: ""
    map["SLL"] = this.SLL.name ?: ""
    map["SOS"] = this.SOS.name ?: ""
    map["SRD"] = this.SRD.name ?: ""
    map["SSP"] = this.SSP.name ?: ""
    map["STD"] = this.STD.name ?: ""
    map["SVC"] = this.SVC.name ?: ""
    map["SYP"] = this.SYP.name ?: ""
    map["SZL"] = this.SZL.name ?: ""
    map["THB"] = this.THB.name ?: ""
    map["TJS"] = this.TJS.name ?: ""
    map["TMT"] = this.TMT.name ?: ""
    map["TND"] = this.TND.name ?: ""
    map["TOP"] = this.TOP.name ?: ""
    map["TRY"] = this.TRY.name ?: ""
    map["TTD"] = this.TTD.name ?: ""
    map["TWD"] = this.TWD.name ?: ""
    map["TZS"] = this.TZS.name ?: ""
    map["UAH"] = this.UAH.name ?: ""
    map["UGX"] = this.UGX.name ?: ""
    map["URY"] = this.URY.name ?: ""
    map["USD"] = this.USD.name ?: ""
    map["UYU"] = this.UYU.name ?: ""
    map["UZS"] = this.UZS.name ?: ""
    map["VEF"] = this.VEF.name ?: ""
    map["VND"] = this.VND.name ?: ""
    map["VUV"] = this.VUV.name ?: ""
    map["WST"] = this.WST.name ?: ""
    map["XAF"] = this.XAF.name ?: ""
    map["XAG"] = this.XAG.name ?: ""
    map["XAU"] = this.XAU.name ?: ""
    map["XCD"] = this.XCD.name ?: ""
    map["XDR"] = this.XDR.name ?: ""
    map["XOF"] = this.XOF.name ?: ""
    map["XPF"] = this.XPF.name ?: ""
    map["XRP"] = this.XRP.name ?: ""
    map["YER"] = this.YER.name ?: ""
    map["ZAR"] = this.ZAR.name ?: ""
    map["ZMK"] = this.ZMK.name ?: ""
    map["ZMW"] = this.ZMW.name ?: ""
    map["ZWL"] = this.ZWL.name ?: ""
    return map
}

//fun Data.toMap() : Map<String, String> {
//    val map = mutableMapOf<String, String>()
//    this::class.memberProperties.map { member ->
//        val key = member.name
//        val value = member.call(this).toString()
//        map.put(key, value)
//    }
//    return map
//}