package com.example.currencyconverter.domain.models.currencydataapiservice

import com.google.gson.annotations.SerializedName

data class Currencies(

    @SerializedName("AED") var AED: String = "",
    @SerializedName("AFN") var AFN: String = "",
    @SerializedName("ALL") var ALL: String = "",
    @SerializedName("AMD") var AMD: String = "",
    @SerializedName("ANG") var ANG: String = "",
    @SerializedName("AOA") var AOA: String = "",
    @SerializedName("ARS") var ARS: String = "",
    @SerializedName("AUD") var AUD: String = "",
    @SerializedName("AWG") var AWG: String = "",
    @SerializedName("AZN") var AZN: String = "",
    @SerializedName("BAM") var BAM: String = "",
    @SerializedName("BBD") var BBD: String = "",
    @SerializedName("BDT") var BDT: String = "",
    @SerializedName("BGN") var BGN: String = "",
    @SerializedName("BHD") var BHD: String = "",
    @SerializedName("BIF") var BIF: String = "",
    @SerializedName("BMD") var BMD: String = "",
    @SerializedName("BND") var BND: String = "",
    @SerializedName("BOB") var BOB: String = "",
    @SerializedName("BRL") var BRL: String = "",
    @SerializedName("BSD") var BSD: String = "",
    @SerializedName("BTC") var BTC: String = "",
    @SerializedName("BTN") var BTN: String = "",
    @SerializedName("BWP") var BWP: String = "",
    @SerializedName("BYN") var BYN: String = "",
    @SerializedName("BYR") var BYR: String = "",
    @SerializedName("BZD") var BZD: String = "",
    @SerializedName("CAD") var CAD: String = "",
    @SerializedName("CDF") var CDF: String = "",
    @SerializedName("CHF") var CHF: String = "",
    @SerializedName("CLF") var CLF: String = "",
    @SerializedName("CLP") var CLP: String = "",
    @SerializedName("CNY") var CNY: String = "",
    @SerializedName("COP") var COP: String = "",
    @SerializedName("CRC") var CRC: String = "",
    @SerializedName("CUC") var CUC: String = "",
    @SerializedName("CUP") var CUP: String = "",
    @SerializedName("CVE") var CVE: String = "",
    @SerializedName("CZK") var CZK: String = "",
    @SerializedName("DJF") var DJF: String = "",
    @SerializedName("DKK") var DKK: String = "",
    @SerializedName("DOP") var DOP: String = "",
    @SerializedName("DZD") var DZD: String = "",
    @SerializedName("EGP") var EGP: String = "",
    @SerializedName("ERN") var ERN: String = "",
    @SerializedName("ETB") var ETB: String = "",
    @SerializedName("EUR") var EUR: String = "",
    @SerializedName("FJD") var FJD: String = "",
    @SerializedName("FKP") var FKP: String = "",
    @SerializedName("GBP") var GBP: String = "",
    @SerializedName("GEL") var GEL: String = "",
    @SerializedName("GGP") var GGP: String = "",
    @SerializedName("GHS") var GHS: String = "",
    @SerializedName("GIP") var GIP: String = "",
    @SerializedName("GMD") var GMD: String = "",
    @SerializedName("GNF") var GNF: String = "",
    @SerializedName("GTQ") var GTQ: String = "",
    @SerializedName("GYD") var GYD: String = "",
    @SerializedName("HKD") var HKD: String = "",
    @SerializedName("HNL") var HNL: String = "",
    @SerializedName("HRK") var HRK: String = "",
    @SerializedName("HTG") var HTG: String = "",
    @SerializedName("HUF") var HUF: String = "",
    @SerializedName("IDR") var IDR: String = "",
    @SerializedName("ILS") var ILS: String = "",
    @SerializedName("IMP") var IMP: String = "",
    @SerializedName("INR") var INR: String = "",
    @SerializedName("IQD") var IQD: String = "",
    @SerializedName("IRR") var IRR: String = "",
    @SerializedName("ISK") var ISK: String = "",
    @SerializedName("JEP") var JEP: String = "",
    @SerializedName("JMD") var JMD: String = "",
    @SerializedName("JOD") var JOD: String = "",
    @SerializedName("JPY") var JPY: String = "",
    @SerializedName("KES") var KES: String = "",
    @SerializedName("KGS") var KGS: String = "",
    @SerializedName("KHR") var KHR: String = "",
    @SerializedName("KMF") var KMF: String = "",
    @SerializedName("KPW") var KPW: String = "",
    @SerializedName("KRW") var KRW: String = "",
    @SerializedName("KWD") var KWD: String = "",
    @SerializedName("KYD") var KYD: String = "",
    @SerializedName("KZT") var KZT: String = "",
    @SerializedName("LAK") var LAK: String = "",
    @SerializedName("LBP") var LBP: String = "",
    @SerializedName("LKR") var LKR: String = "",
    @SerializedName("LRD") var LRD: String = "",
    @SerializedName("LSL") var LSL: String = "",
    @SerializedName("LTL") var LTL: String = "",
    @SerializedName("LVL") var LVL: String = "",
    @SerializedName("LYD") var LYD: String = "",
    @SerializedName("MAD") var MAD: String = "",
    @SerializedName("MDL") var MDL: String = "",
    @SerializedName("MGA") var MGA: String = "",
    @SerializedName("MKD") var MKD: String = "",
    @SerializedName("MMK") var MMK: String = "",
    @SerializedName("MNT") var MNT: String = "",
    @SerializedName("MOP") var MOP: String = "",
    @SerializedName("MRO") var MRO: String = "",
    @SerializedName("MUR") var MUR: String = "",
    @SerializedName("MVR") var MVR: String = "",
    @SerializedName("MWK") var MWK: String = "",
    @SerializedName("MXN") var MXN: String = "",
    @SerializedName("MYR") var MYR: String = "",
    @SerializedName("MZN") var MZN: String = "",
    @SerializedName("NAD") var NAD: String = "",
    @SerializedName("NGN") var NGN: String = "",
    @SerializedName("NIO") var NIO: String = "",
    @SerializedName("NOK") var NOK: String = "",
    @SerializedName("NPR") var NPR: String = "",
    @SerializedName("NZD") var NZD: String = "",
    @SerializedName("OMR") var OMR: String = "",
    @SerializedName("PAB") var PAB: String = "",
    @SerializedName("PEN") var PEN: String = "",
    @SerializedName("PGK") var PGK: String = "",
    @SerializedName("PHP") var PHP: String = "",
    @SerializedName("PKR") var PKR: String = "",
    @SerializedName("PLN") var PLN: String = "",
    @SerializedName("PYG") var PYG: String = "",
    @SerializedName("QAR") var QAR: String = "",
    @SerializedName("RON") var RON: String = "",
    @SerializedName("RSD") var RSD: String = "",
    @SerializedName("RUB") var RUB: String = "",
    @SerializedName("RWF") var RWF: String = "",
    @SerializedName("SAR") var SAR: String = "",
    @SerializedName("SBD") var SBD: String = "",
    @SerializedName("SCR") var SCR: String = "",
    @SerializedName("SDG") var SDG: String = "",
    @SerializedName("SEK") var SEK: String = "",
    @SerializedName("SGD") var SGD: String = "",
    @SerializedName("SHP") var SHP: String = "",
    @SerializedName("SLL") var SLL: String = "",
    @SerializedName("SOS") var SOS: String = "",
    @SerializedName("SRD") var SRD: String = "",
    @SerializedName("STD") var STD: String = "",
    @SerializedName("SVC") var SVC: String = "",
    @SerializedName("SYP") var SYP: String = "",
    @SerializedName("SZL") var SZL: String = "",
    @SerializedName("THB") var THB: String = "",
    @SerializedName("TJS") var TJS: String = "",
    @SerializedName("TMT") var TMT: String = "",
    @SerializedName("TND") var TND: String = "",
    @SerializedName("TOP") var TOP: String = "",
    @SerializedName("TRY") var TRY: String = "",
    @SerializedName("TTD") var TTD: String = "",
    @SerializedName("TWD") var TWD: String = "",
    @SerializedName("TZS") var TZS: String = "",
    @SerializedName("UAH") var UAH: String = "",
    @SerializedName("UGX") var UGX: String = "",
    @SerializedName("USD") var USD: String = "",
    @SerializedName("UYU") var UYU: String = "",
    @SerializedName("UZS") var UZS: String = "",
    @SerializedName("VEF") var VEF: String = "",
    @SerializedName("VND") var VND: String = "",
    @SerializedName("VUV") var VUV: String = "",
    @SerializedName("WST") var WST: String = "",
    @SerializedName("XAF") var XAF: String = "",
    @SerializedName("XAG") var XAG: String = "",
    @SerializedName("XAU") var XAU: String = "",
    @SerializedName("XCD") var XCD: String = "",
    @SerializedName("XDR") var XDR: String = "",
    @SerializedName("XOF") var XOF: String = "",
    @SerializedName("XPF") var XPF: String = "",
    @SerializedName("YER") var YER: String = "",
    @SerializedName("ZAR") var ZAR: String = "",
    @SerializedName("ZMK") var ZMK: String = "",
    @SerializedName("ZMW") var ZMW: String = "",
    @SerializedName("ZWL") var ZWL: String = ""

)

fun Currencies.toMap(): Map<String, String> {
    val map = mutableMapOf<String, String>()
    map["AED"] = this.AED
    map["AFN"] = this.AFN
    map["ALL"] = this.ALL
    map["AMD"] = this.AMD
    map["ANG"] = this.ANG
    map["AOA"] = this.AOA
    map["ARS"] = this.ARS
    map["AUD"] = this.AUD
    map["AWG"] = this.AWG
    map["AZN"] = this.AZN
    map["BAM"] = this.BAM
    map["BBD"] = this.BBD
    map["BDT"] = this.BDT
    map["BGN"] = this.BGN
    map["BHD"] = this.BHD
    map["BIF"] = this.BIF
    map["BMD"] = this.BMD
    map["BND"] = this.BND
    map["BOB"] = this.BOB
    map["BRL"] = this.BRL
    map["BSD"] = this.BSD
    map["BTC"] = this.BTC
    map["BTN"] = this.BTN
    map["BWP"] = this.BWP
    map["BYN"] = this.BYN
    map["BYR"] = this.BYR
    map["BZD"] = this.BZD
    map["CAD"] = this.CAD
    map["CDF"] = this.CDF
    map["CHF"] = this.CHF
    map["CLF"] = this.CLF
    map["CLP"] = this.CLP
    map["CNY"] = this.CNY
    map["COP"] = this.COP
    map["CRC"] = this.CRC
    map["CUC"] = this.CUC
    map["CUP"] = this.CUP
    map["CVE"] = this.CVE
    map["CZK"] = this.CZK
    map["DJF"] = this.DJF
    map["DKK"] = this.DKK
    map["DOP"] = this.DOP
    map["DZD"] = this.DZD
    map["EGP"] = this.EGP
    map["ERN"] = this.ERN
    map["ETB"] = this.ETB
    map["EUR"] = this.EUR
    map["FJD"] = this.FJD
    map["FKP"] = this.FKP
    map["GBP"] = this.GBP
    map["GEL"] = this.GEL
    map["GGP"] = this.GGP
    map["GHS"] = this.GHS
    map["GIP"] = this.GIP
    map["GMD"] = this.GMD
    map["GNF"] = this.GNF
    map["GTQ"] = this.GTQ
    map["GYD"] = this.GYD
    map["HKD"] = this.HKD
    map["HNL"] = this.HNL
    map["HRK"] = this.HRK
    map["HTG"] = this.HTG
    map["HUF"] = this.HUF
    map["IDR"] = this.IDR
    map["ILS"] = this.ILS
    map["IMP"] = this.IMP
    map["INR"] = this.INR
    map["IQD"] = this.IQD
    map["IRR"] = this.IRR
    map["ISK"] = this.ISK
    map["JEP"] = this.JEP
    map["JMD"] = this.JMD
    map["JOD"] = this.JOD
    map["JPY"] = this.JPY
    map["KES"] = this.KES
    map["KGS"] = this.KGS
    map["KHR"] = this.KHR
    map["KMF"] = this.KMF
    map["KPW"] = this.KPW
    map["KRW"] = this.KRW
    map["KWD"] = this.KWD
    map["KYD"] = this.KYD
    map["KZT"] = this.KZT
    map["LAK"] = this.LAK
    map["LBP"] = this.LBP
    map["LKR"] = this.LKR
    map["LRD"] = this.LRD
    map["LSL"] = this.LSL
    map["LTL"] = this.LTL
    map["LVL"] = this.LVL
    map["LYD"] = this.LYD
    map["MAD"] = this.MAD
    map["MDL"] = this.MDL
    map["MGA"] = this.MGA
    map["MKD"] = this.MKD
    map["MMK"] = this.MMK
    map["MNT"] = this.MNT
    map["MOP"] = this.MOP
    map["MRO"] = this.MRO
    map["MUR"] = this.MUR
    map["MVR"] = this.MVR
    map["MWK"] = this.MWK
    map["MXN"] = this.MXN
    map["MYR"] = this.MYR
    map["MZN"] = this.MZN
    map["NAD"] = this.NAD
    map["NGN"] = this.NGN
    map["NIO"] = this.NIO
    map["NOK"] = this.NOK
    map["NPR"] = this.NPR
    map["NZD"] = this.NZD
    map["OMR"] = this.OMR
    map["PAB"] = this.PAB
    map["PEN"] = this.PEN
    map["PGK"] = this.PGK
    map["PHP"] = this.PHP
    map["PKR"] = this.PKR
    map["PLN"] = this.PLN
    map["PYG"] = this.PYG
    map["QAR"] = this.QAR
    map["RON"] = this.RON
    map["RSD"] = this.RSD
    map["RUB"] = this.RUB
    map["RWF"] = this.RWF
    map["SAR"] = this.SAR
    map["SBD"] = this.SBD
    map["SCR"] = this.SCR
    map["SDG"] = this.SDG
    map["SEK"] = this.SEK
    map["SGD"] = this.SGD
    map["SHP"] = this.SHP
    map["SLL"] = this.SLL
    map["SOS"] = this.SOS
    map["SRD"] = this.SRD
    map["STD"] = this.STD
    map["SVC"] = this.SVC
    map["SYP"] = this.SYP
    map["SZL"] = this.SZL
    map["THB"] = this.THB
    map["TJS"] = this.TJS
    map["TMT"] = this.TMT
    map["TND"] = this.TND
    map["TOP"] = this.TOP
    map["TRY"] = this.TRY
    map["TTD"] = this.TTD
    map["TWD"] = this.TWD
    map["TZS"] = this.TZS
    map["UAH"] = this.UAH
    map["UGX"] = this.UGX
    map["USD"] = this.USD
    map["UYU"] = this.UYU
    map["UZS"] = this.UZS
    map["VEF"] = this.VEF
    map["VND"] = this.VND
    map["VUV"] = this.VUV
    map["WST"] = this.WST
    map["XAF"] = this.XAF
    map["XAG"] = this.XAG
    map["XAU"] = this.XAU
    map["XCD"] = this.XCD
    map["XDR"] = this.XDR
    map["XOF"] = this.XOF
    map["XPF"] = this.XPF
    map["YER"] = this.YER
    map["ZAR"] = this.ZAR
    map["ZMK"] = this.ZMK
    map["ZMW"] = this.ZMW
    map["ZWL"] = this.ZWL
    return map
}

//fun Currencies.toMap() : Map<String, String> {
//    val map = mutableMapOf<String, String>()
//    this::class.memberProperties.map { member ->
//        val key = member.name
//        val value = member.call(this).toString()
//        map.put(key, value)
//    }
//    return map
//}