package com.example.currencyconverter.domain.models.currencydataapiservice

import com.example.currencyconverter.network.*
import com.google.gson.annotations.SerializedName


data class Quotes (

    @SerializedName("KZTAED" ) var KZTAED : KZTAED = KZTAED(),
    @SerializedName("KZTAFN" ) var KZTAFN : KZTAFN = KZTAFN(),
    @SerializedName("KZTALL" ) var KZTALL : KZTALL = KZTALL(),
    @SerializedName("KZTAMD" ) var KZTAMD : KZTAMD = KZTAMD(),
    @SerializedName("KZTANG" ) var KZTANG : KZTANG = KZTANG(),
    @SerializedName("KZTAOA" ) var KZTAOA : KZTAOA = KZTAOA(),
    @SerializedName("KZTARS" ) var KZTARS : KZTARS = KZTARS(),
    @SerializedName("KZTAUD" ) var KZTAUD : KZTAUD = KZTAUD(),
    @SerializedName("KZTAWG" ) var KZTAWG : KZTAWG = KZTAWG(),
    @SerializedName("KZTAZN" ) var KZTAZN : KZTAZN = KZTAZN(),
    @SerializedName("KZTBAM" ) var KZTBAM : KZTBAM = KZTBAM(),
    @SerializedName("KZTBBD" ) var KZTBBD : KZTBBD = KZTBBD(),
    @SerializedName("KZTBDT" ) var KZTBDT : KZTBDT = KZTBDT(),
    @SerializedName("KZTBGN" ) var KZTBGN : KZTBGN = KZTBGN(),
    @SerializedName("KZTBHD" ) var KZTBHD : KZTBHD = KZTBHD(),
    @SerializedName("KZTBIF" ) var KZTBIF : KZTBIF = KZTBIF(),
    @SerializedName("KZTBMD" ) var KZTBMD : KZTBMD = KZTBMD(),
    @SerializedName("KZTBND" ) var KZTBND : KZTBND = KZTBND(),
    @SerializedName("KZTBOB" ) var KZTBOB : KZTBOB = KZTBOB(),
    @SerializedName("KZTBRL" ) var KZTBRL : KZTBRL = KZTBRL(),
    @SerializedName("KZTBSD" ) var KZTBSD : KZTBSD = KZTBSD(),
    @SerializedName("KZTBTC" ) var KZTBTC : KZTBTC = KZTBTC(),
    @SerializedName("KZTBTN" ) var KZTBTN : KZTBTN = KZTBTN(),
    @SerializedName("KZTBWP" ) var KZTBWP : KZTBWP = KZTBWP(),
    @SerializedName("KZTBYN" ) var KZTBYN : KZTBYN = KZTBYN(),
    @SerializedName("KZTBYR" ) var KZTBYR : KZTBYR = KZTBYR(),
    @SerializedName("KZTBZD" ) var KZTBZD : KZTBZD = KZTBZD(),
    @SerializedName("KZTCAD" ) var KZTCAD : KZTCAD = KZTCAD(),
    @SerializedName("KZTCDF" ) var KZTCDF : KZTCDF = KZTCDF(),
    @SerializedName("KZTCHF" ) var KZTCHF : KZTCHF = KZTCHF(),
    @SerializedName("KZTCLF" ) var KZTCLF : KZTCLF = KZTCLF(),
    @SerializedName("KZTCLP" ) var KZTCLP : KZTCLP = KZTCLP(),
    @SerializedName("KZTCNY" ) var KZTCNY : KZTCNY = KZTCNY(),
    @SerializedName("KZTCOP" ) var KZTCOP : KZTCOP = KZTCOP(),
    @SerializedName("KZTCRC" ) var KZTCRC : KZTCRC = KZTCRC(),
    @SerializedName("KZTCUC" ) var KZTCUC : KZTCUC = KZTCUC(),
    @SerializedName("KZTCUP" ) var KZTCUP : KZTCUP = KZTCUP(),
    @SerializedName("KZTCVE" ) var KZTCVE : KZTCVE = KZTCVE(),
    @SerializedName("KZTCZK" ) var KZTCZK : KZTCZK = KZTCZK(),
    @SerializedName("KZTDJF" ) var KZTDJF : KZTDJF = KZTDJF(),
    @SerializedName("KZTDKK" ) var KZTDKK : KZTDKK = KZTDKK(),
    @SerializedName("KZTDOP" ) var KZTDOP : KZTDOP = KZTDOP(),
    @SerializedName("KZTDZD" ) var KZTDZD : KZTDZD = KZTDZD(),
    @SerializedName("KZTEGP" ) var KZTEGP : KZTEGP = KZTEGP(),
    @SerializedName("KZTERN" ) var KZTERN : KZTERN = KZTERN(),
    @SerializedName("KZTETB" ) var KZTETB : KZTETB = KZTETB(),
    @SerializedName("KZTEUR" ) var KZTEUR : KZTEUR = KZTEUR(),
    @SerializedName("KZTFJD" ) var KZTFJD : KZTFJD = KZTFJD(),
    @SerializedName("KZTFKP" ) var KZTFKP : KZTFKP = KZTFKP(),
    @SerializedName("KZTGBP" ) var KZTGBP : KZTGBP = KZTGBP(),
    @SerializedName("KZTGEL" ) var KZTGEL : KZTGEL = KZTGEL(),
    @SerializedName("KZTGGP" ) var KZTGGP : KZTGGP = KZTGGP(),
    @SerializedName("KZTGHS" ) var KZTGHS : KZTGHS = KZTGHS(),
    @SerializedName("KZTGIP" ) var KZTGIP : KZTGIP = KZTGIP(),
    @SerializedName("KZTGMD" ) var KZTGMD : KZTGMD = KZTGMD(),
    @SerializedName("KZTGNF" ) var KZTGNF : KZTGNF = KZTGNF(),
    @SerializedName("KZTGTQ" ) var KZTGTQ : KZTGTQ = KZTGTQ(),
    @SerializedName("KZTGYD" ) var KZTGYD : KZTGYD = KZTGYD(),
    @SerializedName("KZTHKD" ) var KZTHKD : KZTHKD = KZTHKD(),
    @SerializedName("KZTHNL" ) var KZTHNL : KZTHNL = KZTHNL(),
    @SerializedName("KZTHRK" ) var KZTHRK : KZTHRK = KZTHRK(),
    @SerializedName("KZTHTG" ) var KZTHTG : KZTHTG = KZTHTG(),
    @SerializedName("KZTHUF" ) var KZTHUF : KZTHUF = KZTHUF(),
    @SerializedName("KZTIDR" ) var KZTIDR : KZTIDR = KZTIDR(),
    @SerializedName("KZTILS" ) var KZTILS : KZTILS = KZTILS(),
    @SerializedName("KZTIMP" ) var KZTIMP : KZTIMP = KZTIMP(),
    @SerializedName("KZTINR" ) var KZTINR : KZTINR = KZTINR(),
    @SerializedName("KZTIQD" ) var KZTIQD : KZTIQD = KZTIQD(),
    @SerializedName("KZTIRR" ) var KZTIRR : KZTIRR = KZTIRR(),
    @SerializedName("KZTISK" ) var KZTISK : KZTISK = KZTISK(),
    @SerializedName("KZTJEP" ) var KZTJEP : KZTJEP = KZTJEP(),
    @SerializedName("KZTJMD" ) var KZTJMD : KZTJMD = KZTJMD(),
    @SerializedName("KZTJOD" ) var KZTJOD : KZTJOD = KZTJOD(),
    @SerializedName("KZTJPY" ) var KZTJPY : KZTJPY = KZTJPY(),
    @SerializedName("KZTKES" ) var KZTKES : KZTKES = KZTKES(),
    @SerializedName("KZTKGS" ) var KZTKGS : KZTKGS = KZTKGS(),
    @SerializedName("KZTKHR" ) var KZTKHR : KZTKHR = KZTKHR(),
    @SerializedName("KZTKMF" ) var KZTKMF : KZTKMF = KZTKMF(),
    @SerializedName("KZTKPW" ) var KZTKPW : KZTKPW = KZTKPW(),
    @SerializedName("KZTKRW" ) var KZTKRW : KZTKRW = KZTKRW(),
    @SerializedName("KZTKWD" ) var KZTKWD : KZTKWD = KZTKWD(),
    @SerializedName("KZTKYD" ) var KZTKYD : KZTKYD = KZTKYD(),
    @SerializedName("KZTKZT" ) var KZTKZT : KZTKZT = KZTKZT(),
    @SerializedName("KZTLAK" ) var KZTLAK : KZTLAK = KZTLAK(),
    @SerializedName("KZTLBP" ) var KZTLBP : KZTLBP = KZTLBP(),
    @SerializedName("KZTLKR" ) var KZTLKR : KZTLKR = KZTLKR(),
    @SerializedName("KZTLRD" ) var KZTLRD : KZTLRD = KZTLRD(),
    @SerializedName("KZTLSL" ) var KZTLSL : KZTLSL = KZTLSL(),
    @SerializedName("KZTLTL" ) var KZTLTL : KZTLTL = KZTLTL(),
    @SerializedName("KZTLVL" ) var KZTLVL : KZTLVL = KZTLVL(),
    @SerializedName("KZTLYD" ) var KZTLYD : KZTLYD = KZTLYD(),
    @SerializedName("KZTMAD" ) var KZTMAD : KZTMAD = KZTMAD(),
    @SerializedName("KZTMDL" ) var KZTMDL : KZTMDL = KZTMDL(),
    @SerializedName("KZTMGA" ) var KZTMGA : KZTMGA = KZTMGA(),
    @SerializedName("KZTMKD" ) var KZTMKD : KZTMKD = KZTMKD(),
    @SerializedName("KZTMMK" ) var KZTMMK : KZTMMK = KZTMMK(),
    @SerializedName("KZTMNT" ) var KZTMNT : KZTMNT = KZTMNT(),
    @SerializedName("KZTMOP" ) var KZTMOP : KZTMOP = KZTMOP(),
    @SerializedName("KZTMRO" ) var KZTMRO : KZTMRO = KZTMRO(),
    @SerializedName("KZTMUR" ) var KZTMUR : KZTMUR = KZTMUR(),
    @SerializedName("KZTMVR" ) var KZTMVR : KZTMVR = KZTMVR(),
    @SerializedName("KZTMWK" ) var KZTMWK : KZTMWK = KZTMWK(),
    @SerializedName("KZTMXN" ) var KZTMXN : KZTMXN = KZTMXN(),
    @SerializedName("KZTMYR" ) var KZTMYR : KZTMYR = KZTMYR(),
    @SerializedName("KZTMZN" ) var KZTMZN : KZTMZN = KZTMZN(),
    @SerializedName("KZTNAD" ) var KZTNAD : KZTNAD = KZTNAD(),
    @SerializedName("KZTNGN" ) var KZTNGN : KZTNGN = KZTNGN(),
    @SerializedName("KZTNIO" ) var KZTNIO : KZTNIO = KZTNIO(),
    @SerializedName("KZTNOK" ) var KZTNOK : KZTNOK = KZTNOK(),
    @SerializedName("KZTNPR" ) var KZTNPR : KZTNPR = KZTNPR(),
    @SerializedName("KZTNZD" ) var KZTNZD : KZTNZD = KZTNZD(),
    @SerializedName("KZTOMR" ) var KZTOMR : KZTOMR = KZTOMR(),
    @SerializedName("KZTPAB" ) var KZTPAB : KZTPAB = KZTPAB(),
    @SerializedName("KZTPEN" ) var KZTPEN : KZTPEN = KZTPEN(),
    @SerializedName("KZTPGK" ) var KZTPGK : KZTPGK = KZTPGK(),
    @SerializedName("KZTPHP" ) var KZTPHP : KZTPHP = KZTPHP(),
    @SerializedName("KZTPKR" ) var KZTPKR : KZTPKR = KZTPKR(),
    @SerializedName("KZTPLN" ) var KZTPLN : KZTPLN = KZTPLN(),
    @SerializedName("KZTPYG" ) var KZTPYG : KZTPYG = KZTPYG(),
    @SerializedName("KZTQAR" ) var KZTQAR : KZTQAR = KZTQAR(),
    @SerializedName("KZTRON" ) var KZTRON : KZTRON = KZTRON(),
    @SerializedName("KZTRSD" ) var KZTRSD : KZTRSD = KZTRSD(),
    @SerializedName("KZTRUB" ) var KZTRUB : KZTRUB = KZTRUB(),
    @SerializedName("KZTRWF" ) var KZTRWF : KZTRWF = KZTRWF(),
    @SerializedName("KZTSAR" ) var KZTSAR : KZTSAR = KZTSAR(),
    @SerializedName("KZTSBD" ) var KZTSBD : KZTSBD = KZTSBD(),
    @SerializedName("KZTSCR" ) var KZTSCR : KZTSCR = KZTSCR(),
    @SerializedName("KZTSDG" ) var KZTSDG : KZTSDG = KZTSDG(),
    @SerializedName("KZTSEK" ) var KZTSEK : KZTSEK = KZTSEK(),
    @SerializedName("KZTSGD" ) var KZTSGD : KZTSGD = KZTSGD(),
    @SerializedName("KZTSHP" ) var KZTSHP : KZTSHP = KZTSHP(),
    @SerializedName("KZTSLL" ) var KZTSLL : KZTSLL = KZTSLL(),
    @SerializedName("KZTSOS" ) var KZTSOS : KZTSOS = KZTSOS(),
    @SerializedName("KZTSRD" ) var KZTSRD : KZTSRD = KZTSRD(),
    @SerializedName("KZTSTD" ) var KZTSTD : KZTSTD = KZTSTD(),
    @SerializedName("KZTSVC" ) var KZTSVC : KZTSVC = KZTSVC(),
    @SerializedName("KZTSYP" ) var KZTSYP : KZTSYP = KZTSYP(),
    @SerializedName("KZTSZL" ) var KZTSZL : KZTSZL = KZTSZL(),
    @SerializedName("KZTTHB" ) var KZTTHB : KZTTHB = KZTTHB(),
    @SerializedName("KZTTJS" ) var KZTTJS : KZTTJS = KZTTJS(),
    @SerializedName("KZTTMT" ) var KZTTMT : KZTTMT = KZTTMT(),
    @SerializedName("KZTTND" ) var KZTTND : KZTTND = KZTTND(),
    @SerializedName("KZTTOP" ) var KZTTOP : KZTTOP = KZTTOP(),
    @SerializedName("KZTTRY" ) var KZTTRY : KZTTRY = KZTTRY(),
    @SerializedName("KZTTTD" ) var KZTTTD : KZTTTD = KZTTTD(),
    @SerializedName("KZTTWD" ) var KZTTWD : KZTTWD = KZTTWD(),
    @SerializedName("KZTTZS" ) var KZTTZS : KZTTZS = KZTTZS(),
    @SerializedName("KZTUAH" ) var KZTUAH : KZTUAH = KZTUAH(),
    @SerializedName("KZTUGX" ) var KZTUGX : KZTUGX = KZTUGX(),
    @SerializedName("KZTUSD" ) var KZTUSD : KZTUSD = KZTUSD(),
    @SerializedName("KZTUYU" ) var KZTUYU : KZTUYU = KZTUYU(),
    @SerializedName("KZTUZS" ) var KZTUZS : KZTUZS = KZTUZS(),
    @SerializedName("KZTVEF" ) var KZTVEF : KZTVEF = KZTVEF(),
    @SerializedName("KZTVND" ) var KZTVND : KZTVND = KZTVND(),
    @SerializedName("KZTVUV" ) var KZTVUV : KZTVUV = KZTVUV(),
    @SerializedName("KZTWST" ) var KZTWST : KZTWST = KZTWST(),
    @SerializedName("KZTXAF" ) var KZTXAF : KZTXAF = KZTXAF(),
    @SerializedName("KZTXAG" ) var KZTXAG : KZTXAG = KZTXAG(),
    @SerializedName("KZTXAU" ) var KZTXAU : KZTXAU = KZTXAU(),
    @SerializedName("KZTXCD" ) var KZTXCD : KZTXCD = KZTXCD(),
    @SerializedName("KZTXDR" ) var KZTXDR : KZTXDR = KZTXDR(),
    @SerializedName("KZTXOF" ) var KZTXOF : KZTXOF = KZTXOF(),
    @SerializedName("KZTXPF" ) var KZTXPF : KZTXPF = KZTXPF(),
    @SerializedName("KZTYER" ) var KZTYER : KZTYER = KZTYER(),
    @SerializedName("KZTZAR" ) var KZTZAR : KZTZAR = KZTZAR(),
    @SerializedName("KZTZMK" ) var KZTZMK : KZTZMK = KZTZMK(),
    @SerializedName("KZTZMW" ) var KZTZMW : KZTZMW = KZTZMW(),
    @SerializedName("KZTZWL" ) var KZTZWL : KZTZWL = KZTZWL()

)

fun Quotes.toMap(): Map<String, Double?> {
    val map = mutableMapOf<String, Double?>()
    map["KZTAED"] = this.KZTAED.startRate
    map["KZTAFN"] = this.KZTAFN.startRate
    map["KZTALL"] = this.KZTALL.startRate
    map["KZTAMD"] = this.KZTAMD.startRate
    map["KZTANG"] = this.KZTANG.startRate
    map["KZTAOA"] = this.KZTAOA.startRate
    map["KZTARS"] = this.KZTARS.startRate
    map["KZTAUD"] = this.KZTAUD.startRate
    map["KZTAWG"] = this.KZTAWG.startRate
    map["KZTAZN"] = this.KZTAZN.startRate
    map["KZTBAM"] = this.KZTBAM.startRate
    map["KZTBBD"] = this.KZTBBD.startRate
    map["KZTBDT"] = this.KZTBDT.startRate
    map["KZTBGN"] = this.KZTBGN.startRate
    map["KZTBHD"] = this.KZTBHD.startRate
    map["KZTBIF"] = this.KZTBIF.startRate
    map["KZTBMD"] = this.KZTBMD.startRate
    map["KZTBND"] = this.KZTBND.startRate
    map["KZTBOB"] = this.KZTBOB.startRate
    map["KZTBRL"] = this.KZTBRL.startRate
    map["KZTBSD"] = this.KZTBSD.startRate
    map["KZTBTC"] = this.KZTBTC.startRate
    map["KZTBTN"] = this.KZTBTN.startRate
    map["KZTBWP"] = this.KZTBWP.startRate
    map["KZTBYN"] = this.KZTBYN.startRate
    map["KZTBYR"] = this.KZTBYR.startRate
    map["KZTBZD"] = this.KZTBZD.startRate
    map["KZTCAD"] = this.KZTCAD.startRate
    map["KZTCDF"] = this.KZTCDF.startRate
    map["KZTCHF"] = this.KZTCHF.startRate
    map["KZTCLF"] = this.KZTCLF.startRate
    map["KZTCLP"] = this.KZTCLP.startRate
    map["KZTCNY"] = this.KZTCNY.startRate
    map["KZTCOP"] = this.KZTCOP.startRate
    map["KZTCRC"] = this.KZTCRC.startRate
    map["KZTCUC"] = this.KZTCUC.startRate
    map["KZTCUP"] = this.KZTCUP.startRate
    map["KZTCVE"] = this.KZTCVE.startRate
    map["KZTCZK"] = this.KZTCZK.startRate
    map["KZTDJF"] = this.KZTDJF.startRate
    map["KZTDKK"] = this.KZTDKK.startRate
    map["KZTDOP"] = this.KZTDOP.startRate
    map["KZTDZD"] = this.KZTDZD.startRate
    map["KZTEGP"] = this.KZTEGP.startRate
    map["KZTERN"] = this.KZTERN.startRate
    map["KZTETB"] = this.KZTETB.startRate
    map["KZTEUR"] = this.KZTEUR.startRate
    map["KZTFJD"] = this.KZTFJD.startRate
    map["KZTFKP"] = this.KZTFKP.startRate
    map["KZTGBP"] = this.KZTGBP.startRate
    map["KZTGEL"] = this.KZTGEL.startRate
    map["KZTGGP"] = this.KZTGGP.startRate
    map["KZTGHS"] = this.KZTGHS.startRate
    map["KZTGIP"] = this.KZTGIP.startRate
    map["KZTGMD"] = this.KZTGMD.startRate
    map["KZTGNF"] = this.KZTGNF.startRate
    map["KZTGTQ"] = this.KZTGTQ.startRate
    map["KZTGYD"] = this.KZTGYD.startRate
    map["KZTHKD"] = this.KZTHKD.startRate
    map["KZTHNL"] = this.KZTHNL.startRate
    map["KZTHRK"] = this.KZTHRK.startRate
    map["KZTHTG"] = this.KZTHTG.startRate
    map["KZTHUF"] = this.KZTHUF.startRate
    map["KZTIDR"] = this.KZTIDR.startRate
    map["KZTILS"] = this.KZTILS.startRate
    map["KZTIMP"] = this.KZTIMP.startRate
    map["KZTINR"] = this.KZTINR.startRate
    map["KZTIQD"] = this.KZTIQD.startRate
    map["KZTIRR"] = this.KZTIRR.startRate
    map["KZTISK"] = this.KZTISK.startRate
    map["KZTJEP"] = this.KZTJEP.startRate
    map["KZTJMD"] = this.KZTJMD.startRate
    map["KZTJOD"] = this.KZTJOD.startRate
    map["KZTJPY"] = this.KZTJPY.startRate
    map["KZTKES"] = this.KZTKES.startRate
    map["KZTKGS"] = this.KZTKGS.startRate
    map["KZTKHR"] = this.KZTKHR.startRate
    map["KZTKMF"] = this.KZTKMF.startRate
    map["KZTKPW"] = this.KZTKPW.startRate
    map["KZTKRW"] = this.KZTKRW.startRate
    map["KZTKWD"] = this.KZTKWD.startRate
    map["KZTKYD"] = this.KZTKYD.startRate
//    map["KZTKZT"] = this.KZTKZT.startRate
    map["KZTLAK"] = this.KZTLAK.startRate
    map["KZTLBP"] = this.KZTLBP.startRate
    map["KZTLKR"] = this.KZTLKR.startRate
    map["KZTLRD"] = this.KZTLRD.startRate
    map["KZTLSL"] = this.KZTLSL.startRate
    map["KZTLTL"] = this.KZTLTL.startRate
    map["KZTLVL"] = this.KZTLVL.startRate
    map["KZTLYD"] = this.KZTLYD.startRate
    map["KZTMAD"] = this.KZTMAD.startRate
    map["KZTMDL"] = this.KZTMDL.startRate
    map["KZTMGA"] = this.KZTMGA.startRate
    map["KZTMKD"] = this.KZTMKD.startRate
    map["KZTMMK"] = this.KZTMMK.startRate
    map["KZTMNT"] = this.KZTMNT.startRate
    map["KZTMOP"] = this.KZTMOP.startRate
    map["KZTMRO"] = this.KZTMRO.startRate
    map["KZTMUR"] = this.KZTMUR.startRate
    map["KZTMVR"] = this.KZTMVR.startRate
    map["KZTMWK"] = this.KZTMWK.startRate
    map["KZTMXN"] = this.KZTMXN.startRate
    map["KZTMYR"] = this.KZTMYR.startRate
    map["KZTMZN"] = this.KZTMZN.startRate
    map["KZTNAD"] = this.KZTNAD.startRate
    map["KZTNGN"] = this.KZTNGN.startRate
    map["KZTNIO"] = this.KZTNIO.startRate
    map["KZTNOK"] = this.KZTNOK.startRate
    map["KZTNPR"] = this.KZTNPR.startRate
    map["KZTNZD"] = this.KZTNZD.startRate
    map["KZTOMR"] = this.KZTOMR.startRate
    map["KZTPAB"] = this.KZTPAB.startRate
    map["KZTPEN"] = this.KZTPEN.startRate
    map["KZTPGK"] = this.KZTPGK.startRate
    map["KZTPHP"] = this.KZTPHP.startRate
    map["KZTPKR"] = this.KZTPKR.startRate
    map["KZTPLN"] = this.KZTPLN.startRate
    map["KZTPYG"] = this.KZTPYG.startRate
    map["KZTQAR"] = this.KZTQAR.startRate
    map["KZTRON"] = this.KZTRON.startRate
    map["KZTRSD"] = this.KZTRSD.startRate
    map["KZTRUB"] = this.KZTRUB.startRate
    map["KZTRWF"] = this.KZTRWF.startRate
    map["KZTSAR"] = this.KZTSAR.startRate
    map["KZTSBD"] = this.KZTSBD.startRate
    map["KZTSCR"] = this.KZTSCR.startRate
    map["KZTSDG"] = this.KZTSDG.startRate
    map["KZTSEK"] = this.KZTSEK.startRate
    map["KZTSGD"] = this.KZTSGD.startRate
    map["KZTSHP"] = this.KZTSHP.startRate
    map["KZTSLL"] = this.KZTSLL.startRate
    map["KZTSOS"] = this.KZTSOS.startRate
    map["KZTSRD"] = this.KZTSRD.startRate
    map["KZTSTD"] = this.KZTSTD.startRate
    map["KZTSVC"] = this.KZTSVC.startRate
    map["KZTSYP"] = this.KZTSYP.startRate
    map["KZTSZL"] = this.KZTSZL.startRate
    map["KZTTHB"] = this.KZTTHB.startRate
    map["KZTTJS"] = this.KZTTJS.startRate
    map["KZTTMT"] = this.KZTTMT.startRate
    map["KZTTND"] = this.KZTTND.startRate
    map["KZTTOP"] = this.KZTTOP.startRate
    map["KZTTRY"] = this.KZTTRY.startRate
    map["KZTTTD"] = this.KZTTTD.startRate
    map["KZTTWD"] = this.KZTTWD.startRate
    map["KZTTZS"] = this.KZTTZS.startRate
    map["KZTUAH"] = this.KZTUAH.startRate
    map["KZTUGX"] = this.KZTUGX.startRate
    map["KZTUSD"] = this.KZTUSD.startRate
    map["KZTUYU"] = this.KZTUYU.startRate
    map["KZTUZS"] = this.KZTUZS.startRate
    map["KZTVEF"] = this.KZTVEF.startRate
    map["KZTVND"] = this.KZTVND.startRate
    map["KZTVUV"] = this.KZTVUV.startRate
    map["KZTWST"] = this.KZTWST.startRate
    map["KZTXAF"] = this.KZTXAF.startRate
    map["KZTXAG"] = this.KZTXAG.startRate
    map["KZTXAU"] = this.KZTXAU.startRate
    map["KZTXCD"] = this.KZTXCD.startRate
    map["KZTXDR"] = this.KZTXDR.startRate
    map["KZTXOF"] = this.KZTXOF.startRate
    map["KZTXPF"] = this.KZTXPF.startRate
    map["KZTYER"] = this.KZTYER.startRate
    map["KZTZAR"] = this.KZTZAR.startRate
    map["KZTZMK"] = this.KZTZMK.startRate
    map["KZTZMW"] = this.KZTZMW.startRate
    map["KZTZWL"] = this.KZTZWL.startRate
    return map
}