package com.example.currencyconverter.domain.models.currencydataapiservice

import com.example.currencyconverter.network.*
import com.google.gson.annotations.SerializedName


data class Quotes (

    @SerializedName("KZTAED" ) var KZTAED : KZTAED = KZTAED(),
    @SerializedName("KZTAFN" ) var KZTAFN : KZTAFN = KZTAFN(),
    @SerializedName("KZTALL" ) var KZTALL : KZTALL = KZTALL(),
    @SerializedName("KZTAMD" ) var KZTAMD : KZTAMD = KZTAMD(),
    @SerializedName("KZTANG" ) var KZTANG : KZTANG = KZTANG(),
    @SerializedName("KZTAOA" ) var KZTAOA : KZTAOA = KZTAOA(),
    @SerializedName("KZTARS" ) var KZTARS : KZTARS = KZTARS(),
    @SerializedName("KZTAUD" ) var KZTAUD : KZTAUD = KZTAUD(),
    @SerializedName("KZTAWG" ) var KZTAWG : KZTAWG = KZTAWG(),
    @SerializedName("KZTAZN" ) var KZTAZN : KZTAZN = KZTAZN(),
    @SerializedName("KZTBAM" ) var KZTBAM : KZTBAM = KZTBAM(),
    @SerializedName("KZTBBD" ) var KZTBBD : KZTBBD = KZTBBD(),
    @SerializedName("KZTBDT" ) var KZTBDT : KZTBDT = KZTBDT(),
    @SerializedName("KZTBGN" ) var KZTBGN : KZTBGN = KZTBGN(),
    @SerializedName("KZTBHD" ) var KZTBHD : KZTBHD = KZTBHD(),
    @SerializedName("KZTBIF" ) var KZTBIF : KZTBIF = KZTBIF(),
    @SerializedName("KZTBMD" ) var KZTBMD : KZTBMD = KZTBMD(),
    @SerializedName("KZTBND" ) var KZTBND : KZTBND = KZTBND(),
    @SerializedName("KZTBOB" ) var KZTBOB : KZTBOB = KZTBOB(),
    @SerializedName("KZTBRL" ) var KZTBRL : KZTBRL = KZTBRL(),
    @SerializedName("KZTBSD" ) var KZTBSD : KZTBSD = KZTBSD(),
    @SerializedName("KZTBTC" ) var KZTBTC : KZTBTC = KZTBTC(),
    @SerializedName("KZTBTN" ) var KZTBTN : KZTBTN = KZTBTN(),
    @SerializedName("KZTBWP" ) var KZTBWP : KZTBWP = KZTBWP(),
    @SerializedName("KZTBYN" ) var KZTBYN : KZTBYN = KZTBYN(),
    @SerializedName("KZTBYR" ) var KZTBYR : KZTBYR = KZTBYR(),
    @SerializedName("KZTBZD" ) var KZTBZD : KZTBZD = KZTBZD(),
    @SerializedName("KZTCAD" ) var KZTCAD : KZTCAD = KZTCAD(),
    @SerializedName("KZTCDF" ) var KZTCDF : KZTCDF = KZTCDF(),
    @SerializedName("KZTCHF" ) var KZTCHF : KZTCHF = KZTCHF(),
    @SerializedName("KZTCLF" ) var KZTCLF : KZTCLF = KZTCLF(),
    @SerializedName("KZTCLP" ) var KZTCLP : KZTCLP = KZTCLP(),
    @SerializedName("KZTCNY" ) var KZTCNY : KZTCNY = KZTCNY(),
    @SerializedName("KZTCOP" ) var KZTCOP : KZTCOP = KZTCOP(),
    @SerializedName("KZTCRC" ) var KZTCRC : KZTCRC = KZTCRC(),
    @SerializedName("KZTCUC" ) var KZTCUC : KZTCUC = KZTCUC(),
    @SerializedName("KZTCUP" ) var KZTCUP : KZTCUP = KZTCUP(),
    @SerializedName("KZTCVE" ) var KZTCVE : KZTCVE = KZTCVE(),
    @SerializedName("KZTCZK" ) var KZTCZK : KZTCZK = KZTCZK(),
    @SerializedName("KZTDJF" ) var KZTDJF : KZTDJF = KZTDJF(),
    @SerializedName("KZTDKK" ) var KZTDKK : KZTDKK = KZTDKK(),
    @SerializedName("KZTDOP" ) var KZTDOP : KZTDOP = KZTDOP(),
    @SerializedName("KZTDZD" ) var KZTDZD : KZTDZD = KZTDZD(),
    @SerializedName("KZTEGP" ) var KZTEGP : KZTEGP = KZTEGP(),
    @SerializedName("KZTERN" ) var KZTERN : KZTERN = KZTERN(),
    @SerializedName("KZTETB" ) var KZTETB : KZTETB = KZTETB(),
    @SerializedName("KZTEUR" ) var KZTEUR : KZTEUR = KZTEUR(),
    @SerializedName("KZTFJD" ) var KZTFJD : KZTFJD = KZTFJD(),
    @SerializedName("KZTFKP" ) var KZTFKP : KZTFKP = KZTFKP(),
    @SerializedName("KZTGBP" ) var KZTGBP : KZTGBP = KZTGBP(),
    @SerializedName("KZTGEL" ) var KZTGEL : KZTGEL = KZTGEL(),
    @SerializedName("KZTGGP" ) var KZTGGP : KZTGGP = KZTGGP(),
    @SerializedName("KZTGHS" ) var KZTGHS : KZTGHS = KZTGHS(),
    @SerializedName("KZTGIP" ) var KZTGIP : KZTGIP = KZTGIP(),
    @SerializedName("KZTGMD" ) var KZTGMD : KZTGMD = KZTGMD(),
    @SerializedName("KZTGNF" ) var KZTGNF : KZTGNF = KZTGNF(),
    @SerializedName("KZTGTQ" ) var KZTGTQ : KZTGTQ = KZTGTQ(),
    @SerializedName("KZTGYD" ) var KZTGYD : KZTGYD = KZTGYD(),
    @SerializedName("KZTHKD" ) var KZTHKD : KZTHKD = KZTHKD(),
    @SerializedName("KZTHNL" ) var KZTHNL : KZTHNL = KZTHNL(),
    @SerializedName("KZTHRK" ) var KZTHRK : KZTHRK = KZTHRK(),
    @SerializedName("KZTHTG" ) var KZTHTG : KZTHTG = KZTHTG(),
    @SerializedName("KZTHUF" ) var KZTHUF : KZTHUF = KZTHUF(),
    @SerializedName("KZTIDR" ) var KZTIDR : KZTIDR = KZTIDR(),
    @SerializedName("KZTILS" ) var KZTILS : KZTILS = KZTILS(),
    @SerializedName("KZTIMP" ) var KZTIMP : KZTIMP = KZTIMP(),
    @SerializedName("KZTINR" ) var KZTINR : KZTINR = KZTINR(),
    @SerializedName("KZTIQD" ) var KZTIQD : KZTIQD = KZTIQD(),
    @SerializedName("KZTIRR" ) var KZTIRR : KZTIRR = KZTIRR(),
    @SerializedName("KZTISK" ) var KZTISK : KZTISK = KZTISK(),
    @SerializedName("KZTJEP" ) var KZTJEP : KZTJEP = KZTJEP(),
    @SerializedName("KZTJMD" ) var KZTJMD : KZTJMD = KZTJMD(),
    @SerializedName("KZTJOD" ) var KZTJOD : KZTJOD = KZTJOD(),
    @SerializedName("KZTJPY" ) var KZTJPY : KZTJPY = KZTJPY(),
    @SerializedName("KZTKES" ) var KZTKES : KZTKES = KZTKES(),
    @SerializedName("KZTKGS" ) var KZTKGS : KZTKGS = KZTKGS(),
    @SerializedName("KZTKHR" ) var KZTKHR : KZTKHR = KZTKHR(),
    @SerializedName("KZTKMF" ) var KZTKMF : KZTKMF = KZTKMF(),
    @SerializedName("KZTKPW" ) var KZTKPW : KZTKPW = KZTKPW(),
    @SerializedName("KZTKRW" ) var KZTKRW : KZTKRW = KZTKRW(),
    @SerializedName("KZTKWD" ) var KZTKWD : KZTKWD = KZTKWD(),
    @SerializedName("KZTKYD" ) var KZTKYD : KZTKYD = KZTKYD(),
    @SerializedName("KZTKZT" ) var KZTKZT : KZTKZT = KZTKZT(),
    @SerializedName("KZTLAK" ) var KZTLAK : KZTLAK = KZTLAK(),
    @SerializedName("KZTLBP" ) var KZTLBP : KZTLBP = KZTLBP(),
    @SerializedName("KZTLKR" ) var KZTLKR : KZTLKR = KZTLKR(),
    @SerializedName("KZTLRD" ) var KZTLRD : KZTLRD = KZTLRD(),
    @SerializedName("KZTLSL" ) var KZTLSL : KZTLSL = KZTLSL(),
    @SerializedName("KZTLTL" ) var KZTLTL : KZTLTL = KZTLTL(),
    @SerializedName("KZTLVL" ) var KZTLVL : KZTLVL = KZTLVL(),
    @SerializedName("KZTLYD" ) var KZTLYD : KZTLYD = KZTLYD(),
    @SerializedName("KZTMAD" ) var KZTMAD : KZTMAD = KZTMAD(),
    @SerializedName("KZTMDL" ) var KZTMDL : KZTMDL = KZTMDL(),
    @SerializedName("KZTMGA" ) var KZTMGA : KZTMGA = KZTMGA(),
    @SerializedName("KZTMKD" ) var KZTMKD : KZTMKD = KZTMKD(),
    @SerializedName("KZTMMK" ) var KZTMMK : KZTMMK = KZTMMK(),
    @SerializedName("KZTMNT" ) var KZTMNT : KZTMNT = KZTMNT(),
    @SerializedName("KZTMOP" ) var KZTMOP : KZTMOP = KZTMOP(),
    @SerializedName("KZTMRO" ) var KZTMRO : KZTMRO = KZTMRO(),
    @SerializedName("KZTMUR" ) var KZTMUR : KZTMUR = KZTMUR(),
    @SerializedName("KZTMVR" ) var KZTMVR : KZTMVR = KZTMVR(),
    @SerializedName("KZTMWK" ) var KZTMWK : KZTMWK = KZTMWK(),
    @SerializedName("KZTMXN" ) var KZTMXN : KZTMXN = KZTMXN(),
    @SerializedName("KZTMYR" ) var KZTMYR : KZTMYR = KZTMYR(),
    @SerializedName("KZTMZN" ) var KZTMZN : KZTMZN = KZTMZN(),
    @SerializedName("KZTNAD" ) var KZTNAD : KZTNAD = KZTNAD(),
    @SerializedName("KZTNGN" ) var KZTNGN : KZTNGN = KZTNGN(),
    @SerializedName("KZTNIO" ) var KZTNIO : KZTNIO = KZTNIO(),
    @SerializedName("KZTNOK" ) var KZTNOK : KZTNOK = KZTNOK(),
    @SerializedName("KZTNPR" ) var KZTNPR : KZTNPR = KZTNPR(),
    @SerializedName("KZTNZD" ) var KZTNZD : KZTNZD = KZTNZD(),
    @SerializedName("KZTOMR" ) var KZTOMR : KZTOMR = KZTOMR(),
    @SerializedName("KZTPAB" ) var KZTPAB : KZTPAB = KZTPAB(),
    @SerializedName("KZTPEN" ) var KZTPEN : KZTPEN = KZTPEN(),
    @SerializedName("KZTPGK" ) var KZTPGK : KZTPGK = KZTPGK(),
    @SerializedName("KZTPHP" ) var KZTPHP : KZTPHP = KZTPHP(),
    @SerializedName("KZTPKR" ) var KZTPKR : KZTPKR = KZTPKR(),
    @SerializedName("KZTPLN" ) var KZTPLN : KZTPLN = KZTPLN(),
    @SerializedName("KZTPYG" ) var KZTPYG : KZTPYG = KZTPYG(),
    @SerializedName("KZTQAR" ) var KZTQAR : KZTQAR = KZTQAR(),
    @SerializedName("KZTRON" ) var KZTRON : KZTRON = KZTRON(),
    @SerializedName("KZTRSD" ) var KZTRSD : KZTRSD = KZTRSD(),
    @SerializedName("KZTRUB" ) var KZTRUB : KZTRUB = KZTRUB(),
    @SerializedName("KZTRWF" ) var KZTRWF : KZTRWF = KZTRWF(),
    @SerializedName("KZTSAR" ) var KZTSAR : KZTSAR = KZTSAR(),
    @SerializedName("KZTSBD" ) var KZTSBD : KZTSBD = KZTSBD(),
    @SerializedName("KZTSCR" ) var KZTSCR : KZTSCR = KZTSCR(),
    @SerializedName("KZTSDG" ) var KZTSDG : KZTSDG = KZTSDG(),
    @SerializedName("KZTSEK" ) var KZTSEK : KZTSEK = KZTSEK(),
    @SerializedName("KZTSGD" ) var KZTSGD : KZTSGD = KZTSGD(),
    @SerializedName("KZTSHP" ) var KZTSHP : KZTSHP = KZTSHP(),
    @SerializedName("KZTSLL" ) var KZTSLL : KZTSLL = KZTSLL(),
    @SerializedName("KZTSOS" ) var KZTSOS : KZTSOS = KZTSOS(),
    @SerializedName("KZTSRD" ) var KZTSRD : KZTSRD = KZTSRD(),
    @SerializedName("KZTSTD" ) var KZTSTD : KZTSTD = KZTSTD(),
    @SerializedName("KZTSVC" ) var KZTSVC : KZTSVC = KZTSVC(),
    @SerializedName("KZTSYP" ) var KZTSYP : KZTSYP = KZTSYP(),
    @SerializedName("KZTSZL" ) var KZTSZL : KZTSZL = KZTSZL(),
    @SerializedName("KZTTHB" ) var KZTTHB : KZTTHB = KZTTHB(),
    @SerializedName("KZTTJS" ) var KZTTJS : KZTTJS = KZTTJS(),
    @SerializedName("KZTTMT" ) var KZTTMT : KZTTMT = KZTTMT(),
    @SerializedName("KZTTND" ) var KZTTND : KZTTND = KZTTND(),
    @SerializedName("KZTTOP" ) var KZTTOP : KZTTOP = KZTTOP(),
    @SerializedName("KZTTRY" ) var KZTTRY : KZTTRY = KZTTRY(),
    @SerializedName("KZTTTD" ) var KZTTTD : KZTTTD = KZTTTD(),
    @SerializedName("KZTTWD" ) var KZTTWD : KZTTWD = KZTTWD(),
    @SerializedName("KZTTZS" ) var KZTTZS : KZTTZS = KZTTZS(),
    @SerializedName("KZTUAH" ) var KZTUAH : KZTUAH = KZTUAH(),
    @SerializedName("KZTUGX" ) var KZTUGX : KZTUGX = KZTUGX(),
    @SerializedName("KZTUSD" ) var KZTUSD : KZTUSD = KZTUSD(),
    @SerializedName("KZTUYU" ) var KZTUYU : KZTUYU = KZTUYU(),
    @SerializedName("KZTUZS" ) var KZTUZS : KZTUZS = KZTUZS(),
    @SerializedName("KZTVEF" ) var KZTVEF : KZTVEF = KZTVEF(),
    @SerializedName("KZTVND" ) var KZTVND : KZTVND = KZTVND(),
    @SerializedName("KZTVUV" ) var KZTVUV : KZTVUV = KZTVUV(),
    @SerializedName("KZTWST" ) var KZTWST : KZTWST = KZTWST(),
    @SerializedName("KZTXAF" ) var KZTXAF : KZTXAF = KZTXAF(),
    @SerializedName("KZTXAG" ) var KZTXAG : KZTXAG = KZTXAG(),
    @SerializedName("KZTXAU" ) var KZTXAU : KZTXAU = KZTXAU(),
    @SerializedName("KZTXCD" ) var KZTXCD : KZTXCD = KZTXCD(),
    @SerializedName("KZTXDR" ) var KZTXDR : KZTXDR = KZTXDR(),
    @SerializedName("KZTXOF" ) var KZTXOF : KZTXOF = KZTXOF(),
    @SerializedName("KZTXPF" ) var KZTXPF : KZTXPF = KZTXPF(),
    @SerializedName("KZTYER" ) var KZTYER : KZTYER = KZTYER(),
    @SerializedName("KZTZAR" ) var KZTZAR : KZTZAR = KZTZAR(),
    @SerializedName("KZTZMK" ) var KZTZMK : KZTZMK = KZTZMK(),
    @SerializedName("KZTZMW" ) var KZTZMW : KZTZMW = KZTZMW(),
    @SerializedName("KZTZWL" ) var KZTZWL : KZTZWL = KZTZWL()

)

fun Quotes.toMap(source: String): Map<String, Double?> {
    val map = mutableMapOf<String, Double?>()
    map["${source}AED"] = this.KZTAED.startRate
    map["${source}AFN"] = this.KZTAFN.startRate
    map["${source}ALL"] = this.KZTALL.startRate
    map["${source}AMD"] = this.KZTAMD.startRate
    map["${source}ANG"] = this.KZTANG.startRate
    map["${source}AOA"] = this.KZTAOA.startRate
    map["${source}ARS"] = this.KZTARS.startRate
    map["${source}AUD"] = this.KZTAUD.startRate
    map["${source}AWG"] = this.KZTAWG.startRate
    map["${source}AZN"] = this.KZTAZN.startRate
    map["${source}BAM"] = this.KZTBAM.startRate
    map["${source}BBD"] = this.KZTBBD.startRate
    map["${source}BDT"] = this.KZTBDT.startRate
    map["${source}BGN"] = this.KZTBGN.startRate
    map["${source}BHD"] = this.KZTBHD.startRate
    map["${source}BIF"] = this.KZTBIF.startRate
    map["${source}BMD"] = this.KZTBMD.startRate
    map["${source}BND"] = this.KZTBND.startRate
    map["${source}BOB"] = this.KZTBOB.startRate
    map["${source}BRL"] = this.KZTBRL.startRate
    map["${source}BSD"] = this.KZTBSD.startRate
    map["${source}BTC"] = this.KZTBTC.startRate
    map["${source}BTN"] = this.KZTBTN.startRate
    map["${source}BWP"] = this.KZTBWP.startRate
    map["${source}BYN"] = this.KZTBYN.startRate
    map["${source}BYR"] = this.KZTBYR.startRate
    map["${source}BZD"] = this.KZTBZD.startRate
    map["${source}CAD"] = this.KZTCAD.startRate
    map["${source}CDF"] = this.KZTCDF.startRate
    map["${source}CHF"] = this.KZTCHF.startRate
    map["${source}CLF"] = this.KZTCLF.startRate
    map["${source}CLP"] = this.KZTCLP.startRate
    map["${source}CNY"] = this.KZTCNY.startRate
    map["${source}COP"] = this.KZTCOP.startRate
    map["${source}CRC"] = this.KZTCRC.startRate
    map["${source}CUC"] = this.KZTCUC.startRate
    map["${source}CUP"] = this.KZTCUP.startRate
    map["${source}CVE"] = this.KZTCVE.startRate
    map["${source}CZK"] = this.KZTCZK.startRate
    map["${source}DJF"] = this.KZTDJF.startRate
    map["${source}DKK"] = this.KZTDKK.startRate
    map["${source}DOP"] = this.KZTDOP.startRate
    map["${source}DZD"] = this.KZTDZD.startRate
    map["${source}EGP"] = this.KZTEGP.startRate
    map["${source}ERN"] = this.KZTERN.startRate
    map["${source}ETB"] = this.KZTETB.startRate
    map["${source}EUR"] = this.KZTEUR.startRate
    map["${source}FJD"] = this.KZTFJD.startRate
    map["${source}FKP"] = this.KZTFKP.startRate
    map["${source}GBP"] = this.KZTGBP.startRate
    map["${source}GEL"] = this.KZTGEL.startRate
    map["${source}GGP"] = this.KZTGGP.startRate
    map["${source}GHS"] = this.KZTGHS.startRate
    map["${source}GIP"] = this.KZTGIP.startRate
    map["${source}GMD"] = this.KZTGMD.startRate
    map["${source}GNF"] = this.KZTGNF.startRate
    map["${source}GTQ"] = this.KZTGTQ.startRate
    map["${source}GYD"] = this.KZTGYD.startRate
    map["${source}HKD"] = this.KZTHKD.startRate
    map["${source}HNL"] = this.KZTHNL.startRate
    map["${source}HRK"] = this.KZTHRK.startRate
    map["${source}HTG"] = this.KZTHTG.startRate
    map["${source}HUF"] = this.KZTHUF.startRate
    map["${source}IDR"] = this.KZTIDR.startRate
    map["${source}ILS"] = this.KZTILS.startRate
    map["${source}IMP"] = this.KZTIMP.startRate
    map["${source}INR"] = this.KZTINR.startRate
    map["${source}IQD"] = this.KZTIQD.startRate
    map["${source}IRR"] = this.KZTIRR.startRate
    map["${source}ISK"] = this.KZTISK.startRate
    map["${source}JEP"] = this.KZTJEP.startRate
    map["${source}JMD"] = this.KZTJMD.startRate
    map["${source}JOD"] = this.KZTJOD.startRate
    map["${source}JPY"] = this.KZTJPY.startRate
    map["${source}KES"] = this.KZTKES.startRate
    map["${source}KGS"] = this.KZTKGS.startRate
    map["${source}KHR"] = this.KZTKHR.startRate
    map["${source}KMF"] = this.KZTKMF.startRate
    map["${source}KPW"] = this.KZTKPW.startRate
    map["${source}KRW"] = this.KZTKRW.startRate
    map["${source}KWD"] = this.KZTKWD.startRate
    map["${source}KYD"] = this.KZTKYD.startRate
//    map["${source}KZT"] = this.KZTKZT.startRate
    map["${source}LAK"] = this.KZTLAK.startRate
    map["${source}LBP"] = this.KZTLBP.startRate
    map["${source}LKR"] = this.KZTLKR.startRate
    map["${source}LRD"] = this.KZTLRD.startRate
    map["${source}LSL"] = this.KZTLSL.startRate
    map["${source}LTL"] = this.KZTLTL.startRate
    map["${source}LVL"] = this.KZTLVL.startRate
    map["${source}LYD"] = this.KZTLYD.startRate
    map["${source}MAD"] = this.KZTMAD.startRate
    map["${source}MDL"] = this.KZTMDL.startRate
    map["${source}MGA"] = this.KZTMGA.startRate
    map["${source}MKD"] = this.KZTMKD.startRate
    map["${source}MMK"] = this.KZTMMK.startRate
    map["${source}MNT"] = this.KZTMNT.startRate
    map["${source}MOP"] = this.KZTMOP.startRate
    map["${source}MRO"] = this.KZTMRO.startRate
    map["${source}MUR"] = this.KZTMUR.startRate
    map["${source}MVR"] = this.KZTMVR.startRate
    map["${source}MWK"] = this.KZTMWK.startRate
    map["${source}MXN"] = this.KZTMXN.startRate
    map["${source}MYR"] = this.KZTMYR.startRate
    map["${source}MZN"] = this.KZTMZN.startRate
    map["${source}NAD"] = this.KZTNAD.startRate
    map["${source}NGN"] = this.KZTNGN.startRate
    map["${source}NIO"] = this.KZTNIO.startRate
    map["${source}NOK"] = this.KZTNOK.startRate
    map["${source}NPR"] = this.KZTNPR.startRate
    map["${source}NZD"] = this.KZTNZD.startRate
    map["${source}OMR"] = this.KZTOMR.startRate
    map["${source}PAB"] = this.KZTPAB.startRate
    map["${source}PEN"] = this.KZTPEN.startRate
    map["${source}PGK"] = this.KZTPGK.startRate
    map["${source}PHP"] = this.KZTPHP.startRate
    map["${source}PKR"] = this.KZTPKR.startRate
    map["${source}PLN"] = this.KZTPLN.startRate
    map["${source}PYG"] = this.KZTPYG.startRate
    map["${source}QAR"] = this.KZTQAR.startRate
    map["${source}RON"] = this.KZTRON.startRate
    map["${source}RSD"] = this.KZTRSD.startRate
    map["${source}RUB"] = this.KZTRUB.startRate
    map["${source}RWF"] = this.KZTRWF.startRate
    map["${source}SAR"] = this.KZTSAR.startRate
    map["${source}SBD"] = this.KZTSBD.startRate
    map["${source}SCR"] = this.KZTSCR.startRate
    map["${source}SDG"] = this.KZTSDG.startRate
    map["${source}SEK"] = this.KZTSEK.startRate
    map["${source}SGD"] = this.KZTSGD.startRate
    map["${source}SHP"] = this.KZTSHP.startRate
    map["${source}SLL"] = this.KZTSLL.startRate
    map["${source}SOS"] = this.KZTSOS.startRate
    map["${source}SRD"] = this.KZTSRD.startRate
    map["${source}STD"] = this.KZTSTD.startRate
    map["${source}SVC"] = this.KZTSVC.startRate
    map["${source}SYP"] = this.KZTSYP.startRate
    map["${source}SZL"] = this.KZTSZL.startRate
    map["${source}THB"] = this.KZTTHB.startRate
    map["${source}TJS"] = this.KZTTJS.startRate
    map["${source}TMT"] = this.KZTTMT.startRate
    map["${source}TND"] = this.KZTTND.startRate
    map["${source}TOP"] = this.KZTTOP.startRate
    map["${source}TRY"] = this.KZTTRY.startRate
    map["${source}TTD"] = this.KZTTTD.startRate
    map["${source}TWD"] = this.KZTTWD.startRate
    map["${source}TZS"] = this.KZTTZS.startRate
    map["${source}UAH"] = this.KZTUAH.startRate
    map["${source}UGX"] = this.KZTUGX.startRate
    map["${source}USD"] = this.KZTUSD.startRate
    map["${source}UYU"] = this.KZTUYU.startRate
    map["${source}UZS"] = this.KZTUZS.startRate
    map["${source}VEF"] = this.KZTVEF.startRate
    map["${source}VND"] = this.KZTVND.startRate
    map["${source}VUV"] = this.KZTVUV.startRate
    map["${source}WST"] = this.KZTWST.startRate
    map["${source}XAF"] = this.KZTXAF.startRate
    map["${source}XAG"] = this.KZTXAG.startRate
    map["${source}XAU"] = this.KZTXAU.startRate
    map["${source}XCD"] = this.KZTXCD.startRate
    map["${source}XDR"] = this.KZTXDR.startRate
    map["${source}XOF"] = this.KZTXOF.startRate
    map["${source}XPF"] = this.KZTXPF.startRate
    map["${source}YER"] = this.KZTYER.startRate
    map["${source}ZAR"] = this.KZTZAR.startRate
    map["${source}ZMK"] = this.KZTZMK.startRate
    map["${source}ZMW"] = this.KZTZMW.startRate
    map["${source}ZWL"] = this.KZTZWL.startRate
    return map
}