package com.example.currencyconverter.domain.models.currencyapiservice.rate

import com.example.currencyconverter.domain.models.currencyapiservice.rate.rates.*
import com.google.gson.annotations.SerializedName


data class Data (

    @SerializedName("AED" ) var AED : AED? = AED(),
    @SerializedName("AFN" ) var AFN : AFN? = AFN(),
    @SerializedName("ALL" ) var ALL : ALL? = ALL(),
    @SerializedName("AMD" ) var AMD : AMD? = AMD(),
    @SerializedName("ANG" ) var ANG : ANG? = ANG(),
    @SerializedName("AOA" ) var AOA : AOA? = AOA(),
    @SerializedName("ARS" ) var ARS : ARS? = ARS(),
    @SerializedName("AUD" ) var AUD : AUD? = AUD(),
    @SerializedName("AWG" ) var AWG : AWG? = AWG(),
    @SerializedName("AZN" ) var AZN : AZN? = AZN(),
    @SerializedName("BAM" ) var BAM : BAM? = BAM(),
    @SerializedName("BBD" ) var BBD : BBD? = BBD(),
    @SerializedName("BDT" ) var BDT : BDT? = BDT(),
    @SerializedName("BGN" ) var BGN : BGN? = BGN(),
    @SerializedName("BHD" ) var BHD : BHD? = BHD(),
    @SerializedName("BIF" ) var BIF : BIF? = BIF(),
    @SerializedName("BMD" ) var BMD : BMD? = BMD(),
    @SerializedName("BND" ) var BND : BND? = BND(),
    @SerializedName("BOB" ) var BOB : BOB? = BOB(),
    @SerializedName("BRL" ) var BRL : BRL? = BRL(),
    @SerializedName("BSD" ) var BSD : BSD? = BSD(),
    @SerializedName("BTC" ) var BTC : BTC? = BTC(),
    @SerializedName("BTN" ) var BTN : BTN? = BTN(),
    @SerializedName("BWP" ) var BWP : BWP? = BWP(),
    @SerializedName("BYN" ) var BYN : BYN? = BYN(),
    @SerializedName("BYR" ) var BYR : BYR? = BYR(),
    @SerializedName("BZD" ) var BZD : BZD? = BZD(),
    @SerializedName("CAD" ) var CAD : CAD? = CAD(),
    @SerializedName("CDF" ) var CDF : CDF? = CDF(),
    @SerializedName("CHF" ) var CHF : CHF? = CHF(),
    @SerializedName("CLF" ) var CLF : CLF? = CLF(),
    @SerializedName("CLP" ) var CLP : CLP? = CLP(),
    @SerializedName("CNY" ) var CNY : CNY? = CNY(),
    @SerializedName("COP" ) var COP : COP? = COP(),
    @SerializedName("CRC" ) var CRC : CRC? = CRC(),
    @SerializedName("CUC" ) var CUC : CUC? = CUC(),
    @SerializedName("CUP" ) var CUP : CUP? = CUP(),
    @SerializedName("CVE" ) var CVE : CVE? = CVE(),
    @SerializedName("CZK" ) var CZK : CZK? = CZK(),
    @SerializedName("DJF" ) var DJF : DJF? = DJF(),
    @SerializedName("DKK" ) var DKK : DKK? = DKK(),
    @SerializedName("DOP" ) var DOP : DOP? = DOP(),
    @SerializedName("DZD" ) var DZD : DZD? = DZD(),
    @SerializedName("EGP" ) var EGP : EGP? = EGP(),
    @SerializedName("ETB" ) var ETB : ETB? = ETB(),
    @SerializedName("EUR" ) var EUR : EUR? = EUR(),
    @SerializedName("FJD" ) var FJD : FJD? = FJD(),
    @SerializedName("GBP" ) var GBP : GBP? = GBP(),
    @SerializedName("GEL" ) var GEL : GEL? = GEL(),
    @SerializedName("GHS" ) var GHS : GHS? = GHS(),
    @SerializedName("GMD" ) var GMD : GMD? = GMD(),
    @SerializedName("GNF" ) var GNF : GNF? = GNF(),
    @SerializedName("GTQ" ) var GTQ : GTQ? = GTQ(),
    @SerializedName("GYD" ) var GYD : GYD? = GYD(),
    @SerializedName("HKD" ) var HKD : HKD? = HKD(),
    @SerializedName("HNL" ) var HNL : HNL? = HNL(),
    @SerializedName("HRK" ) var HRK : HRK? = HRK(),
    @SerializedName("HTG" ) var HTG : HTG? = HTG(),
    @SerializedName("HUF" ) var HUF : HUF? = HUF(),
    @SerializedName("IDR" ) var IDR : IDR? = IDR(),
    @SerializedName("ILS" ) var ILS : ILS? = ILS(),
    @SerializedName("INR" ) var INR : INR? = INR(),
    @SerializedName("IQD" ) var IQD : IQD? = IQD(),
    @SerializedName("IRR" ) var IRR : IRR? = IRR(),
    @SerializedName("ISK" ) var ISK : ISK? = ISK(),
    @SerializedName("JMD" ) var JMD : JMD? = JMD(),
    @SerializedName("JOD" ) var JOD : JOD? = JOD(),
    @SerializedName("JPY" ) var JPY : JPY? = JPY(),
    @SerializedName("KES" ) var KES : KES? = KES(),
    @SerializedName("KGS" ) var KGS : KGS? = KGS(),
    @SerializedName("KHR" ) var KHR : KHR? = KHR(),
    @SerializedName("KMF" ) var KMF : KMF? = KMF(),
    @SerializedName("KRW" ) var KRW : KRW? = KRW(),
    @SerializedName("KWD" ) var KWD : KWD? = KWD(),
    @SerializedName("KYD" ) var KYD : KYD? = KYD(),
    @SerializedName("KZT" ) var KZT : KZT? = KZT(),
    @SerializedName("LAK" ) var LAK : LAK? = LAK(),
    @SerializedName("LBP" ) var LBP : LBP? = LBP(),
    @SerializedName("LKR" ) var LKR : LKR? = LKR(),
    @SerializedName("LRD" ) var LRD : LRD? = LRD(),
    @SerializedName("LSL" ) var LSL : LSL? = LSL(),
    @SerializedName("LTL" ) var LTL : LTL? = LTL(),
    @SerializedName("LVL" ) var LVL : LVL? = LVL(),
    @SerializedName("LYD" ) var LYD : LYD? = LYD(),
    @SerializedName("MAD" ) var MAD : MAD? = MAD(),
    @SerializedName("MDL" ) var MDL : MDL? = MDL(),
    @SerializedName("MGA" ) var MGA : MGA? = MGA(),
    @SerializedName("MKD" ) var MKD : MKD? = MKD(),
    @SerializedName("MMK" ) var MMK : MMK? = MMK(),
    @SerializedName("MOP" ) var MOP : MOP? = MOP(),
    @SerializedName("MRO" ) var MRO : MRO? = MRO(),
    @SerializedName("MUR" ) var MUR : MUR? = MUR(),
    @SerializedName("MVR" ) var MVR : MVR? = MVR(),
    @SerializedName("MWK" ) var MWK : MWK? = MWK(),
    @SerializedName("MXN" ) var MXN : MXN? = MXN(),
    @SerializedName("MYR" ) var MYR : MYR? = MYR(),
    @SerializedName("MZN" ) var MZN : MZN? = MZN(),
    @SerializedName("NAD" ) var NAD : NAD? = NAD(),
    @SerializedName("NGN" ) var NGN : NGN? = NGN(),
    @SerializedName("NIO" ) var NIO : NIO? = NIO(),
    @SerializedName("NOK" ) var NOK : NOK? = NOK(),
    @SerializedName("NPR" ) var NPR : NPR? = NPR(),
    @SerializedName("NZD" ) var NZD : NZD? = NZD(),
    @SerializedName("OMR" ) var OMR : OMR? = OMR(),
    @SerializedName("PAB" ) var PAB : PAB? = PAB(),
    @SerializedName("PEN" ) var PEN : PEN? = PEN(),
    @SerializedName("PGK" ) var PGK : PGK? = PGK(),
    @SerializedName("PHP" ) var PHP : PHP? = PHP(),
    @SerializedName("PKR" ) var PKR : PKR? = PKR(),
    @SerializedName("PLN" ) var PLN : PLN? = PLN(),
    @SerializedName("PYG" ) var PYG : PYG? = PYG(),
    @SerializedName("QAR" ) var QAR : QAR? = QAR(),
    @SerializedName("RON" ) var RON : RON? = RON(),
    @SerializedName("RSD" ) var RSD : RSD? = RSD(),
    @SerializedName("RUB" ) var RUB : RUB? = RUB(),
    @SerializedName("RWF" ) var RWF : RWF? = RWF(),
    @SerializedName("SAR" ) var SAR : SAR? = SAR(),
    @SerializedName("SBD" ) var SBD : SBD? = SBD(),
    @SerializedName("SCR" ) var SCR : SCR? = SCR(),
    @SerializedName("SDG" ) var SDG : SDG? = SDG(),
    @SerializedName("SEK" ) var SEK : SEK? = SEK(),
    @SerializedName("SGD" ) var SGD : SGD? = SGD(),
    @SerializedName("SHP" ) var SHP : SHP? = SHP(),
    @SerializedName("SLL" ) var SLL : SLL? = SLL(),
    @SerializedName("SOS" ) var SOS : SOS? = SOS(),
    @SerializedName("SRD" ) var SRD : SRD? = SRD(),
    @SerializedName("STD" ) var STD : STD? = STD(),
    @SerializedName("SVC" ) var SVC : SVC? = SVC(),
    @SerializedName("SZL" ) var SZL : SZL? = SZL(),
    @SerializedName("THB" ) var THB : THB? = THB(),
    @SerializedName("TJS" ) var TJS : TJS? = TJS(),
    @SerializedName("TMT" ) var TMT : TMT? = TMT(),
    @SerializedName("TND" ) var TND : TND? = TND(),
    @SerializedName("TOP" ) var TOP : TOP? = TOP(),
    @SerializedName("TRY" ) var TRY : TRY? = TRY(),
    @SerializedName("TTD" ) var TTD : TTD? = TTD(),
    @SerializedName("TWD" ) var TWD : TWD? = TWD(),
    @SerializedName("TZS" ) var TZS : TZS? = TZS(),
    @SerializedName("UAH" ) var UAH : UAH? = UAH(),
    @SerializedName("UGX" ) var UGX : UGX? = UGX(),
    @SerializedName("USD" ) var USD : USD? = USD(),
    @SerializedName("UYU" ) var UYU : UYU? = UYU(),
    @SerializedName("UZS" ) var UZS : UZS? = UZS(),
    @SerializedName("VND" ) var VND : VND? = VND(),
    @SerializedName("XAF" ) var XAF : XAF? = XAF(),
    @SerializedName("XCD" ) var XCD : XCD? = XCD(),
    @SerializedName("XDR" ) var XDR : XDR? = XDR(),
    @SerializedName("XOF" ) var XOF : XOF? = XOF(),
    @SerializedName("XPF" ) var XPF : XPF? = XPF(),
    @SerializedName("YER" ) var YER : YER? = YER(),
    @SerializedName("ZAR" ) var ZAR : ZAR? = ZAR(),
    @SerializedName("ZMK" ) var ZMK : ZMK? = ZMK(),
    @SerializedName("ZMW" ) var ZMW : ZMW? = ZMW(),
    @SerializedName("ZWL" ) var ZWL : ZWL? = ZWL()

)

fun Data.toMap(source: String): Map<String, Double?> {
    val map = mutableMapOf<String, Double?>()
    map["${source}AED"] = AED().value
    map["${source}AFN"] = AFN().value
    map["${source}ALL"] = ALL().value
    map["${source}AMD"] = AMD().value
    map["${source}ANG"] = ANG().value
    map["${source}AOA"] = AOA().value
    map["${source}ARS"] = ARS().value
    map["${source}AUD"] = AUD().value
    map["${source}AWG"] = AWG().value
    map["${source}AZN"] = AZN().value
    map["${source}BAM"] = BAM().value
    map["${source}BBD"] = BBD().value
    map["${source}BDT"] = BDT().value
    map["${source}BGN"] = BGN().value
    map["${source}BHD"] = BHD().value
    map["${source}BIF"] = BIF().value
    map["${source}BMD"] = BMD().value
    map["${source}BND"] = BND().value
    map["${source}BOB"] = BOB().value
    map["${source}BRL"] = BRL().value
    map["${source}BSD"] = BSD().value
    map["${source}BTC"] = BTC().value
    map["${source}BTN"] = BTN().value
    map["${source}BWP"] = BWP().value
    map["${source}BYN"] = BYN().value
    map["${source}BYR"] = BYR().value
    map["${source}BZD"] = BZD().value
    map["${source}CAD"] = CAD().value
    map["${source}CDF"] = CDF().value
    map["${source}CHF"] = CHF().value
    map["${source}CLF"] = CLF().value
    map["${source}CLP"] = CLP().value
    map["${source}CNY"] = CNY().value
    map["${source}COP"] = COP().value
    map["${source}CRC"] = CRC().value
    map["${source}CUC"] = CUC().value
    map["${source}CUP"] = CUP().value
    map["${source}CVE"] = CVE().value
    map["${source}CZK"] = CZK().value
    map["${source}DJF"] = DJF().value
    map["${source}DKK"] = DKK().value
    map["${source}DOP"] = DOP().value
    map["${source}DZD"] = DZD().value
    map["${source}EGP"] = EGP().value
    map["${source}ETB"] = ETB().value
    map["${source}EUR"] = EUR().value
    map["${source}FJD"] = FJD().value
    map["${source}GBP"] = GBP().value
    map["${source}GEL"] = GEL().value
    map["${source}GHS"] = GHS().value
    map["${source}GMD"] = GMD().value
    map["${source}GNF"] = GNF().value
    map["${source}GTQ"] = GTQ().value
    map["${source}GYD"] = GYD().value
    map["${source}HKD"] = HKD().value
    map["${source}HNL"] = HNL().value
    map["${source}HRK"] = HRK().value
    map["${source}HTG"] = HTG().value
    map["${source}HUF"] = HUF().value
    map["${source}IDR"] = IDR().value
    map["${source}ILS"] = ILS().value
    map["${source}INR"] = INR().value
    map["${source}IQD"] = IQD().value
    map["${source}IRR"] = IRR().value
    map["${source}ISK"] = ISK().value
    map["${source}JMD"] = JMD().value
    map["${source}JOD"] = JOD().value
    map["${source}JPY"] = JPY().value
    map["${source}KES"] = KES().value
    map["${source}KGS"] = KGS().value
    map["${source}KHR"] = KHR().value
    map["${source}KMF"] = KMF().value
    map["${source}KRW"] = KRW().value
    map["${source}KWD"] = KWD().value
    map["${source}KYD"] = KYD().value
//    map["${source}KZT"] = KZT().value
    map["${source}LAK"] = LAK().value
    map["${source}LBP"] = LBP().value
    map["${source}LKR"] = LKR().value
    map["${source}LRD"] = LRD().value
    map["${source}LSL"] = LSL().value
    map["${source}LTL"] = LTL().value
    map["${source}LVL"] = LVL().value
    map["${source}LYD"] = LYD().value
    map["${source}MAD"] = MAD().value
    map["${source}MDL"] = MDL().value
    map["${source}MGA"] = MGA().value
    map["${source}MKD"] = MKD().value
    map["${source}MMK"] = MMK().value
    map["${source}MOP"] = MOP().value
    map["${source}MRO"] = MRO().value
    map["${source}MUR"] = MUR().value
    map["${source}MVR"] = MVR().value
    map["${source}MWK"] = MWK().value
    map["${source}MXN"] = MXN().value
    map["${source}MYR"] = MYR().value
    map["${source}MZN"] = MZN().value
    map["${source}NAD"] = NAD().value
    map["${source}NGN"] = NGN().value
    map["${source}NIO"] = NIO().value
    map["${source}NOK"] = NOK().value
    map["${source}NPR"] = NPR().value
    map["${source}NZD"] = NZD().value
    map["${source}OMR"] = OMR().value
    map["${source}PAB"] = PAB().value
    map["${source}PEN"] = PEN().value
    map["${source}PGK"] = PGK().value
    map["${source}PHP"] = PHP().value
    map["${source}PKR"] = PKR().value
    map["${source}PLN"] = PLN().value
    map["${source}PYG"] = PYG().value
    map["${source}QAR"] = QAR().value
    map["${source}RON"] = RON().value
    map["${source}RSD"] = RSD().value
    map["${source}RUB"] = RUB().value
    map["${source}RWF"] = RWF().value
    map["${source}SAR"] = SAR().value
    map["${source}SBD"] = SBD().value
    map["${source}SCR"] = SCR().value
    map["${source}SDG"] = SDG().value
    map["${source}SEK"] = SEK().value
    map["${source}SGD"] = SGD().value
    map["${source}SHP"] = SHP().value
    map["${source}SLL"] = SLL().value
    map["${source}SOS"] = SOS().value
    map["${source}SRD"] = SRD().value
    map["${source}STD"] = STD().value
    map["${source}SVC"] = SVC().value
    map["${source}SZL"] = SZL().value
    map["${source}THB"] = THB().value
    map["${source}TJS"] = TJS().value
    map["${source}TMT"] = TMT().value
    map["${source}TND"] = TND().value
    map["${source}TOP"] = TOP().value
    map["${source}TRY"] = TRY().value
    map["${source}TTD"] = TTD().value
    map["${source}TWD"] = TWD().value
    map["${source}TZS"] = TZS().value
    map["${source}UAH"] = UAH().value
    map["${source}UGX"] = UGX().value
    map["${source}USD"] = USD().value
    map["${source}UYU"] = UYU().value
    map["${source}UZS"] = UZS().value
    map["${source}VND"] = VND().value
    map["${source}XAF"] = XAF().value
    map["${source}XCD"] = XCD().value
    map["${source}XDR"] = XDR().value
    map["${source}XOF"] = XOF().value
    map["${source}XPF"] = XPF().value
    map["${source}YER"] = YER().value
    map["${source}ZAR"] = ZAR().value
    map["${source}ZMK"] = ZMK().value
    map["${source}ZMW"] = ZMW().value
    map["${source}ZWL"] = ZWL().value
    return map
}