package com.example.currencyconverter.domain.models.currencyapiservice.rate

import com.example.currencyconverter.domain.models.currencyapiservice.rate.rates.*
import com.google.gson.annotations.SerializedName


data class Data(

    @SerializedName("AED") var AED: AED = AED(),
    @SerializedName("AFN") var AFN: AFN = AFN(),
    @SerializedName("ALL") var ALL: ALL = ALL(),
    @SerializedName("AMD") var AMD: AMD = AMD(),
    @SerializedName("ANG") var ANG: ANG = ANG(),
    @SerializedName("AOA") var AOA: AOA = AOA(),
    @SerializedName("ARS") var ARS: ARS = ARS(),
    @SerializedName("AUD") var AUD: AUD = AUD(),
    @SerializedName("AWG") var AWG: AWG = AWG(),
    @SerializedName("AZN") var AZN: AZN = AZN(),
    @SerializedName("BAM") var BAM: BAM = BAM(),
    @SerializedName("BBD") var BBD: BBD = BBD(),
    @SerializedName("BDT") var BDT: BDT = BDT(),
    @SerializedName("BGN") var BGN: BGN = BGN(),
    @SerializedName("BHD") var BHD: BHD = BHD(),
    @SerializedName("BIF") var BIF: BIF = BIF(),
    @SerializedName("BMD") var BMD: BMD = BMD(),
    @SerializedName("BND") var BND: BND = BND(),
    @SerializedName("BOB") var BOB: BOB = BOB(),
    @SerializedName("BRL") var BRL: BRL = BRL(),
    @SerializedName("BSD") var BSD: BSD = BSD(),
    @SerializedName("BTC") var BTC: BTC = BTC(),
    @SerializedName("BTN") var BTN: BTN = BTN(),
    @SerializedName("BWP") var BWP: BWP = BWP(),
    @SerializedName("BYN") var BYN: BYN = BYN(),
    @SerializedName("BYR") var BYR: BYR = BYR(),
    @SerializedName("BZD") var BZD: BZD = BZD(),
    @SerializedName("CAD") var CAD: CAD = CAD(),
    @SerializedName("CDF") var CDF: CDF = CDF(),
    @SerializedName("CHF") var CHF: CHF = CHF(),
    @SerializedName("CLF") var CLF: CLF = CLF(),
    @SerializedName("CLP") var CLP: CLP = CLP(),
    @SerializedName("CNY") var CNY: CNY = CNY(),
    @SerializedName("COP") var COP: COP = COP(),
    @SerializedName("CRC") var CRC: CRC = CRC(),
    @SerializedName("CUC") var CUC: CUC = CUC(),
    @SerializedName("CUP") var CUP: CUP = CUP(),
    @SerializedName("CVE") var CVE: CVE = CVE(),
    @SerializedName("CZK") var CZK: CZK = CZK(),
    @SerializedName("DJF") var DJF: DJF = DJF(),
    @SerializedName("DKK") var DKK: DKK = DKK(),
    @SerializedName("DOP") var DOP: DOP = DOP(),
    @SerializedName("DZD") var DZD: DZD = DZD(),
    @SerializedName("EGP") var EGP: EGP = EGP(),
    @SerializedName("ETB") var ETB: ETB = ETB(),
    @SerializedName("EUR") var EUR: EUR = EUR(),
    @SerializedName("FJD") var FJD: FJD = FJD(),
    @SerializedName("GBP") var GBP: GBP = GBP(),
    @SerializedName("GEL") var GEL: GEL = GEL(),
    @SerializedName("GHS") var GHS: GHS = GHS(),
    @SerializedName("GMD") var GMD: GMD = GMD(),
    @SerializedName("GNF") var GNF: GNF = GNF(),
    @SerializedName("GTQ") var GTQ: GTQ = GTQ(),
    @SerializedName("GYD") var GYD: GYD = GYD(),
    @SerializedName("HKD") var HKD: HKD = HKD(),
    @SerializedName("HNL") var HNL: HNL = HNL(),
    @SerializedName("HRK") var HRK: HRK = HRK(),
    @SerializedName("HTG") var HTG: HTG = HTG(),
    @SerializedName("HUF") var HUF: HUF = HUF(),
    @SerializedName("IDR") var IDR: IDR = IDR(),
    @SerializedName("ILS") var ILS: ILS = ILS(),
    @SerializedName("INR") var INR: INR = INR(),
    @SerializedName("IQD") var IQD: IQD = IQD(),
    @SerializedName("IRR") var IRR: IRR = IRR(),
    @SerializedName("ISK") var ISK: ISK = ISK(),
    @SerializedName("JMD") var JMD: JMD = JMD(),
    @SerializedName("JOD") var JOD: JOD = JOD(),
    @SerializedName("JPY") var JPY: JPY = JPY(),
    @SerializedName("KES") var KES: KES = KES(),
    @SerializedName("KGS") var KGS: KGS = KGS(),
    @SerializedName("KHR") var KHR: KHR = KHR(),
    @SerializedName("KMF") var KMF: KMF = KMF(),
    @SerializedName("KRW") var KRW: KRW = KRW(),
    @SerializedName("KWD") var KWD: KWD = KWD(),
    @SerializedName("KYD") var KYD: KYD = KYD(),
    @SerializedName("KZT") var KZT: KZT = KZT(),
    @SerializedName("LAK") var LAK: LAK = LAK(),
    @SerializedName("LBP") var LBP: LBP = LBP(),
    @SerializedName("LKR") var LKR: LKR = LKR(),
    @SerializedName("LRD") var LRD: LRD = LRD(),
    @SerializedName("LSL") var LSL: LSL = LSL(),
    @SerializedName("LTL") var LTL: LTL = LTL(),
    @SerializedName("LVL") var LVL: LVL = LVL(),
    @SerializedName("LYD") var LYD: LYD = LYD(),
    @SerializedName("MAD") var MAD: MAD = MAD(),
    @SerializedName("MDL") var MDL: MDL = MDL(),
    @SerializedName("MGA") var MGA: MGA = MGA(),
    @SerializedName("MKD") var MKD: MKD = MKD(),
    @SerializedName("MMK") var MMK: MMK = MMK(),
    @SerializedName("MOP") var MOP: MOP = MOP(),
    @SerializedName("MRO") var MRO: MRO = MRO(),
    @SerializedName("MUR") var MUR: MUR = MUR(),
    @SerializedName("MVR") var MVR: MVR = MVR(),
    @SerializedName("MWK") var MWK: MWK = MWK(),
    @SerializedName("MXN") var MXN: MXN = MXN(),
    @SerializedName("MYR") var MYR: MYR = MYR(),
    @SerializedName("MZN") var MZN: MZN = MZN(),
    @SerializedName("NAD") var NAD: NAD = NAD(),
    @SerializedName("NGN") var NGN: NGN = NGN(),
    @SerializedName("NIO") var NIO: NIO = NIO(),
    @SerializedName("NOK") var NOK: NOK = NOK(),
    @SerializedName("NPR") var NPR: NPR = NPR(),
    @SerializedName("NZD") var NZD: NZD = NZD(),
    @SerializedName("OMR") var OMR: OMR = OMR(),
    @SerializedName("PAB") var PAB: PAB = PAB(),
    @SerializedName("PEN") var PEN: PEN = PEN(),
    @SerializedName("PGK") var PGK: PGK = PGK(),
    @SerializedName("PHP") var PHP: PHP = PHP(),
    @SerializedName("PKR") var PKR: PKR = PKR(),
    @SerializedName("PLN") var PLN: PLN = PLN(),
    @SerializedName("PYG") var PYG: PYG = PYG(),
    @SerializedName("QAR") var QAR: QAR = QAR(),
    @SerializedName("RON") var RON: RON = RON(),
    @SerializedName("RSD") var RSD: RSD = RSD(),
    @SerializedName("RUB") var RUB: RUB = RUB(),
    @SerializedName("RWF") var RWF: RWF = RWF(),
    @SerializedName("SAR") var SAR: SAR = SAR(),
    @SerializedName("SBD") var SBD: SBD = SBD(),
    @SerializedName("SCR") var SCR: SCR = SCR(),
    @SerializedName("SDG") var SDG: SDG = SDG(),
    @SerializedName("SEK") var SEK: SEK = SEK(),
    @SerializedName("SGD") var SGD: SGD = SGD(),
    @SerializedName("SHP") var SHP: SHP = SHP(),
    @SerializedName("SLL") var SLL: SLL = SLL(),
    @SerializedName("SOS") var SOS: SOS = SOS(),
    @SerializedName("SRD") var SRD: SRD = SRD(),
    @SerializedName("STD") var STD: STD = STD(),
    @SerializedName("SVC") var SVC: SVC = SVC(),
    @SerializedName("SZL") var SZL: SZL = SZL(),
    @SerializedName("THB") var THB: THB = THB(),
    @SerializedName("TJS") var TJS: TJS = TJS(),
    @SerializedName("TMT") var TMT: TMT = TMT(),
    @SerializedName("TND") var TND: TND = TND(),
    @SerializedName("TOP") var TOP: TOP = TOP(),
    @SerializedName("TRY") var TRY: TRY = TRY(),
    @SerializedName("TTD") var TTD: TTD = TTD(),
    @SerializedName("TWD") var TWD: TWD = TWD(),
    @SerializedName("TZS") var TZS: TZS = TZS(),
    @SerializedName("UAH") var UAH: UAH = UAH(),
    @SerializedName("UGX") var UGX: UGX = UGX(),
    @SerializedName("USD") var USD: USD = USD(),
    @SerializedName("UYU") var UYU: UYU = UYU(),
    @SerializedName("UZS") var UZS: UZS = UZS(),
    @SerializedName("VND") var VND: VND = VND(),
    @SerializedName("XAF") var XAF: XAF = XAF(),
    @SerializedName("XCD") var XCD: XCD = XCD(),
    @SerializedName("XDR") var XDR: XDR = XDR(),
    @SerializedName("XOF") var XOF: XOF = XOF(),
    @SerializedName("XPF") var XPF: XPF = XPF(),
    @SerializedName("YER") var YER: YER = YER(),
    @SerializedName("ZAR") var ZAR: ZAR = ZAR(),
    @SerializedName("ZMK") var ZMK: ZMK = ZMK(),
    @SerializedName("ZMW") var ZMW: ZMW = ZMW(),
    @SerializedName("ZWL") var ZWL: ZWL = ZWL()

)

fun Data.toMap(source: String): Map<String, Double?> {
    val map = mutableMapOf<String, Double?>()
    map["${source}AED"] = this.AED.value
    map["${source}AFN"] = this.AFN.value
    map["${source}ALL"] = this.ALL.value
    map["${source}AMD"] = this.AMD.value
    map["${source}ANG"] = this.ANG.value
    map["${source}AOA"] = this.AOA.value
    map["${source}ARS"] = this.ARS.value
    map["${source}AUD"] = this.AUD.value
    map["${source}AWG"] = this.AWG.value
    map["${source}AZN"] = this.AZN.value
    map["${source}BAM"] = this.BAM.value
    map["${source}BBD"] = this.BBD.value
    map["${source}BDT"] = this.BDT.value
    map["${source}BGN"] = this.BGN.value
    map["${source}BHD"] = this.BHD.value
    map["${source}BIF"] = this.BIF.value
    map["${source}BMD"] = this.BMD.value
    map["${source}BND"] = this.BND.value
    map["${source}BOB"] = this.BOB.value
    map["${source}BRL"] = this.BRL.value
    map["${source}BSD"] = this.BSD.value
    map["${source}BTC"] = this.BTC.value
    map["${source}BTN"] = this.BTN.value
    map["${source}BWP"] = this.BWP.value
    map["${source}BYN"] = this.BYN.value
    map["${source}BYR"] = this.BYR.value
    map["${source}BZD"] = this.BZD.value
    map["${source}CAD"] = this.CAD.value
    map["${source}CDF"] = this.CDF.value
    map["${source}CHF"] = this.CHF.value
    map["${source}CLF"] = this.CLF.value
    map["${source}CLP"] = this.CLP.value
    map["${source}CNY"] = this.CNY.value
    map["${source}COP"] = this.COP.value
    map["${source}CRC"] = this.CRC.value
    map["${source}CUC"] = this.CUC.value
    map["${source}CUP"] = this.CUP.value
    map["${source}CVE"] = this.CVE.value
    map["${source}CZK"] = this.CZK.value
    map["${source}DJF"] = this.DJF.value
    map["${source}DKK"] = this.DKK.value
    map["${source}DOP"] = this.DOP.value
    map["${source}DZD"] = this.DZD.value
    map["${source}EGP"] = this.EGP.value
    map["${source}ETB"] = this.ETB.value
    map["${source}EUR"] = this.EUR.value
    map["${source}FJD"] = this.FJD.value
    map["${source}GBP"] = this.GBP.value
    map["${source}GEL"] = this.GEL.value
    map["${source}GHS"] = this.GHS.value
    map["${source}GMD"] = this.GMD.value
    map["${source}GNF"] = this.GNF.value
    map["${source}GTQ"] = this.GTQ.value
    map["${source}GYD"] = this.GYD.value
    map["${source}HKD"] = this.HKD.value
    map["${source}HNL"] = this.HNL.value
    map["${source}HRK"] = this.HRK.value
    map["${source}HTG"] = this.HTG.value
    map["${source}HUF"] = this.HUF.value
    map["${source}IDR"] = this.IDR.value
    map["${source}ILS"] = this.ILS.value
    map["${source}INR"] = this.INR.value
    map["${source}IQD"] = this.IQD.value
    map["${source}IRR"] = this.IRR.value
    map["${source}ISK"] = this.ISK.value
    map["${source}JMD"] = this.JMD.value
    map["${source}JOD"] = this.JOD.value
    map["${source}JPY"] = this.JPY.value
    map["${source}KES"] = this.KES.value
    map["${source}KGS"] = this.KGS.value
    map["${source}KHR"] = this.KHR.value
    map["${source}KMF"] = this.KMF.value
    map["${source}KRW"] = this.KRW.value
    map["${source}KWD"] = this.KWD.value
    map["${source}KYD"] = this.KYD.value
//    map["${source}KZT"] = this.KZT.value
    map["${source}LAK"] = this.LAK.value
    map["${source}LBP"] = this.LBP.value
    map["${source}LKR"] = this.LKR.value
    map["${source}LRD"] = this.LRD.value
    map["${source}LSL"] = this.LSL.value
    map["${source}LTL"] = this.LTL.value
    map["${source}LVL"] = this.LVL.value
    map["${source}LYD"] = this.LYD.value
    map["${source}MAD"] = this.MAD.value
    map["${source}MDL"] = this.MDL.value
    map["${source}MGA"] = this.MGA.value
    map["${source}MKD"] = this.MKD.value
    map["${source}MMK"] = this.MMK.value
    map["${source}MOP"] = this.MOP.value
    map["${source}MRO"] = this.MRO.value
    map["${source}MUR"] = this.MUR.value
    map["${source}MVR"] = this.MVR.value
    map["${source}MWK"] = this.MWK.value
    map["${source}MXN"] = this.MXN.value
    map["${source}MYR"] = this.MYR.value
    map["${source}MZN"] = this.MZN.value
    map["${source}NAD"] = this.NAD.value
    map["${source}NGN"] = this.NGN.value
    map["${source}NIO"] = this.NIO.value
    map["${source}NOK"] = this.NOK.value
    map["${source}NPR"] = this.NPR.value
    map["${source}NZD"] = this.NZD.value
    map["${source}OMR"] = this.OMR.value
    map["${source}PAB"] = this.PAB.value
    map["${source}PEN"] = this.PEN.value
    map["${source}PGK"] = this.PGK.value
    map["${source}PHP"] = this.PHP.value
    map["${source}PKR"] = this.PKR.value
    map["${source}PLN"] = this.PLN.value
    map["${source}PYG"] = this.PYG.value
    map["${source}QAR"] = this.QAR.value
    map["${source}RON"] = this.RON.value
    map["${source}RSD"] = this.RSD.value
    map["${source}RUB"] = this.RUB.value
    map["${source}RWF"] = this.RWF.value
    map["${source}SAR"] = this.SAR.value
    map["${source}SBD"] = this.SBD.value
    map["${source}SCR"] = this.SCR.value
    map["${source}SDG"] = this.SDG.value
    map["${source}SEK"] = this.SEK.value
    map["${source}SGD"] = this.SGD.value
    map["${source}SHP"] = this.SHP.value
    map["${source}SLL"] = this.SLL.value
    map["${source}SOS"] = this.SOS.value
    map["${source}SRD"] = this.SRD.value
    map["${source}STD"] = this.STD.value
    map["${source}SVC"] = this.SVC.value
    map["${source}SZL"] = this.SZL.value
    map["${source}THB"] = this.THB.value
    map["${source}TJS"] = this.TJS.value
    map["${source}TMT"] = this.TMT.value
    map["${source}TND"] = this.TND.value
    map["${source}TOP"] = this.TOP.value
    map["${source}TRY"] = this.TRY.value
    map["${source}TTD"] = this.TTD.value
    map["${source}TWD"] = this.TWD.value
    map["${source}TZS"] = this.TZS.value
    map["${source}UAH"] = this.UAH.value
    map["${source}UGX"] = this.UGX.value
    map["${source}USD"] = this.USD.value
    map["${source}UYU"] = this.UYU.value
    map["${source}UZS"] = this.UZS.value
    map["${source}VND"] = this.VND.value
    map["${source}XAF"] = this.XAF.value
    map["${source}XCD"] = this.XCD.value
    map["${source}XDR"] = this.XDR.value
    map["${source}XOF"] = this.XOF.value
    map["${source}XPF"] = this.XPF.value
    map["${source}YER"] = this.YER.value
    map["${source}ZAR"] = this.ZAR.value
    map["${source}ZMK"] = this.ZMK.value
    map["${source}ZMW"] = this.ZMW.value
    map["${source}ZWL"] = this.ZWL.value
    return map
}